### ISSUE TITLE
Direct stream meet HDFS LeaseExpiredException might becase of spark speculation is on

### ISSUE THREAD

**Issue by Myasuka** [Azure/azure-event-hubs-spark#132]
Currently, `EventHubDirectDStream` will save its progress to HDFS with [ProgressWriter](https://github.com/hdinsight/spark-eventhubs/blob/master/core/src/main/scala/org/apache/spark/eventhubscommon/progress/ProgressWriter.scala#L43), from the code we can see `ProgressWriter` will override to `tempProgressTrackingPointPath`. 
If we turn spark speculation on, another the same task-2 will be triggered in some case. However, task-2 will override to the same path which leads to task-1 meet HDFS LeaseExpiredException 
~~~
org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException: No lease on xxxx: File does not exist.
~~~

**Comment by CodingCat** [comment]
thanks for reporting this, let me think about it

**Comment by CodingCat** [comment]
did the task fail?

**Comment by Myasuka** [comment]
@CodingCat As far as I could remember, the task will fail and leads to the whole job failure in the end.

**Comment by sabeegrewal** [comment]
I'm going to close this issue because the progress tracker is currently being deprecated. We'll have documentation out soon about what offset management options will be available. Thanks for reporting this!
