### ISSUE TITLE
Backpressure support

### ISSUE THREAD

**Issue by slyons** [Azure/azure-event-hubs-spark#14]
Currently when connecting to EventHubs it appears the source appears to grab every message available for the partition. It would be useful to limit the amount of incoming messages processed at a time, which would lead to backpressure support as is supported by other streaming sources such as Kafka.

**Comment by arijitt** [comment]
Did you set the event rate per partition and check if each batch is honoring the rate?

**Comment by slyons** [comment]
Where do you set the events per partition?

**Comment by arijitt** [comment]
All configurations are set in SparkConf in the application code.

**Comment by slyons** [comment]
Is this documented anywhere?

And is there plans to support the Spark backpressure system?

**Comment by slyons** [comment]
Regardless of this configuration, is your team aware of the backpressure system within Spark and are you considering supporting it in the plugin?

**Comment by arijitt** [comment]
Sorry I thought this is resolved. It is already supported by the receiver framework of Spark. Please set the following in SparkConf in you application:

"spark.streaming.backpressure.enabled" to "true"
"spark.streaming.receiver.maxRate" to something like "100000"

The rate is events per partition per second. Have you tried these settings in you application code and did they not work?

**Comment by renepajta** [comment]
Hi all, 

is it really supported? Looking at the implementation, I have some doubts

`override protected[streaming] val rateController: Option[RateController] = {
    if (RateController.isBackPressureEnabled(ssc.sparkContext.conf)) {
      logWarning("rateController: BackPressure is not currently supported.")
    }
    None
  }`
