### ISSUE TITLE
When enqueue time argument is higher than what's available in EH, create an empty batch

### ISSUE THREAD

**Issue by sabeegrewal** [Azure/azure-event-hubs-spark#171]
When passing in a timestamp to enqueue time, sometimes the job fails with the following error if event hubs does not have data:

java.lang.IllegalArgumentException: requirement failed: you cannot pass in an enqueue time which is later than the highest enqueue time in event hubs

Can this be changed so that an empty batch is created?

**Comment by vkunniyur** [comment]
Hi sabeegrewal , any idea as to when this issue will be addressed?

**Comment by sabeegrewal** [comment]
Early Q1 of 2018! I'm happy to chat in detail on gitter :) I'm sure you've seen the link by now, but here it is again: https://gitter.im/azure-event-hubs-spark/Lobby
