### ISSUE TITLE
Data being received by Spark streaming job is 4 minutes behind current UTC

### ISSUE THREAD

**Issue by scriperdjq** [Azure/azure-event-hubs-spark#216]
This may not be a bug and could just be config issue. 

We have Azure IOTHub setup with time-series data being pushed to it almost instantaneously. Also a spark streaming job is configured to consume the data at batch interval of 10 seconds. Ideally the job should be receiving data without major lags. But we see a lag of 4 minutes being introduced by something and we have no clue why. 

We followed the examples and below are the eventhub parameters & spark config,
```
val eventHubsParameters = Map[String, String](
      "eventhubs.namespace" -> EVENTHUB_NAMESPACE,
      "eventhubs.name" -> EVENTHUB_NAME,
      "eventhubs.policyname" -> POLICY_NAME,
      "eventhubs.policykey" -> POLICY_KEY,
      "eventhubs.consumergroup" -> CONSUMER_GROUP,
      "eventhubs.partition.count" -> PARTITION_COUNT
    )
val sparkConfiguration : SparkConf = EventHubsUtils.initializeSparkStreamingConfigurations

    sparkConfiguration.setAppName(this.getClass.getSimpleName)
    sparkConfiguration.set("spark.streaming.driver.writeAheadLog.allowBatching", "true")
    sparkConfiguration.set("spark.streaming.driver.writeAheadLog.batchingTimeout", "60000")
    sparkConfiguration.set("spark.streaming.receiver.writeAheadLog.enable", "true")
    sparkConfiguration.set("spark.streaming.driver.writeAheadLog.closeFileAfterWrite", "true")
    sparkConfiguration.set("spark.streaming.receiver.writeAheadLog.closeFileAfterWrite", "true")
    sparkConfiguration.set("spark.streaming.stopGracefullyOnShutdown", "true")
```

Can somebody please help in figuring out the issue?

- Spark version
 2.1.0
- spark-eventhubs artifactId and version
com.microsoft.azure:spark-streaming-eventhubs_2.11:2.1.5

**Comment by sabeegrewal** [comment]
Hey there! Thanks for using the library! :) 

The current version of the library is entirely dependent on the `ProgressTracker`. At the end of the RDD, the offset and sequence number of the _last_ event in each RDD partition is persisted. On the start of the next batch, the Driver will read those offsets and sequence numbers and use them as the starting points for the next RDD. This disallows batch intervals as low as the one you've set. You'd need to set it to something like 5 minutes. 

With that said, this library can definitely be implemented without all of these HDFS reads/writes that come with the progress tracker. The progress tracker is from an old implementation from previous owners, and I'm currently rewriting the library without the progress tracker. That should be done in just over a month, and it should allow streaming jobs with batch intervals which are under 10 seconds. 

There's a lot more information I can add, but I'll leave it at this. Please ask any and all questions you have!!

**Comment by scriperdjq** [comment]
Thanks for the fast response @sabeegrewal. We do have requirement of live streaming of data. Glad to know you are already working on this. Will wait for the next release.

**Comment by sabeegrewal** [comment]
No worries! Again, we appreciate your interest. :) 

I'll leave this issue open until lower batch intervals are feasible.
