### ISSUE TITLE
Error creating DStream on Azure Databricks

### ISSUE THREAD

**Issue by syedhassaanahmed** [Azure/azure-event-hubs-spark#222]
Hi,

Following [this example](https://github.com/Azure/azure-event-hubs-spark/blob/master/examples/src/main/scala/com/microsoft/spark/streaming/examples/directdstream/MultiStreamsJoin.scala) I'm trying to create `EventHub DStream` but running into the exception below. Here is my code;
```java
val ssc = new StreamingContext(sc, Seconds(batchIntervalSeconds))
ssc.checkpoint(checkpointDir)
  
val inputDStream = EventHubsUtils.createDirectStreams(
  ssc,
  eventhubsNamespace,
  progressDir,
  Map(eventhubsName -> eventhubsParameters))
```

- Actual behavior
``` 
java.lang.NoSuchMethodError: org.apache.spark.streaming.eventhubs.EventHubDirectDStream$.$lessinit$greater$default$5()Lscala/Function5;
	at org.apache.spark.streaming.eventhubs.EventHubsUtils$.createDirectStreams(EventHubsUtils.scala:52)
```

- Expected behavior
`DStream` is successfully created

- Spark version
Databricks Runtime 3.5
Apache Spark 2.2.1
Scala 2.11

- spark-eventhubs artifactId and version
com.microsoft.azure:azure-eventhubs-spark_2.11:jar:2.1.6

- Dependencies automatically pulled by Databricks
proton-j-0.22.0.jar
slf4j-api-1.7.25.jar

**Comment by sabeegrewal** [comment]
Hey Syed! The signature for `createDirectStream` is the following:

```scala
 def createDirectStreams(ssc: StreamingContext,
                          progressDir: String,
                          ehParams: Map[String, Map[String, String]]): EventHubDirectDStream
```

So, if you drop the `eventhubsNamespace` argument, this should work for you. Also, you should switch to `com.microsoft.azure:azure-eventhubs-databricks_2.11:jar:3.4.0`. We don't have a 3.5 yet, but this will work. 

With all that said, I recently took over this repo around Novemeber. I've been re-working it since then and we'll relaunch in mid-Feb with improved code and documentation! Let me know if you have any further questions!

**Comment by syedhassaanahmed** [comment]
Hi @sabeegrewal 

Thanks for the response.

Are you sure about the signature of `createDirectStream` in latest published version on Maven i.e. `com.microsoft.azure:azure-eventhubs-spark_2.11:jar:2.1.6` ? I get "_not enough arguments..._" error if I drop the `eventhubsNamespace` argument. In any case the exception mentioned in my original post is a runtime error not caused by missing arguments.

Regarding `com.microsoft.azure:azure-eventhubs-databricks_2.11:jar:3.4.0`. The class `EventHubsUtils` doesn't exist in that library. Do you know how can I create `EventHub DStreams` on Databricks?

**Comment by sabeegrewal** [comment]
Hi @syedhassaanahmed - I'm fairly sure for both packages. The path the EventHubUtils is `com.microsoft.azure.eventhubs.common.EventHubsUtils`. Can you try again and let me know how it goes?

**Comment by syedhassaanahmed** [comment]
Hi @sabeegrewal I've peeked into the eventhubs-databricks.jar and the correct namespace there is `org.apache.spark.eventhubs.common.EventHubsUtils`. Thanks for the help!

**Comment by sabeegrewal** [comment]
Ah yes, you're right. Glad it's working! I'll be updating documentation over the next couple weeks so this process is a little clearer.
