### ISSUE TITLE
Spark Event hub streaming losing data

### ISSUE THREAD

**Issue by khajaasmath786** [Azure/azure-event-hubs-spark#225]
Hi,

I have been using azure event hub library in development environment. we are still trying to evalute based on the data loss issues. I was able to run streaming application successfully and read data from azure event hub. Problem we are facing is due to KMS issue in cloudera environment so we have to restart spark streaming application daily.

when we restart , we are losing the data with this library. We tried all options of graceful shutdown but no luck with the data loss. is there a efficent way to stop the streaming application with azure event hub and make sure we dont lose any data.

Thanks,
Asmath

**Comment by sabeegrewal** [comment]
Hey @khajaasmath786, what exactly are you seeing? Are the events received after restart not picking up where you left off? Or do you see data come into Spark but never make it downstream? 

Also, how are you starting the job? Are you passing offsets? Enqueued times? 

We are re-launching with a new library (the first release from the EventHubs team) and I want to make sure the issues you are seeing don't exist in the coming release!

**Comment by khajaasmath786** [comment]
Hi Sabeegrewal,

I am seeing similar issue link stated in below but for azure event hub.

https://stackoverflow.com/questions/39905455/spark-streaming-with-kafka-restarting-from-checkpoint

I am seeing zero event records after restarting .(restarted after 6 hours ). do you know how to resolve it. I have to rely on this until we migrate completely to 2.2 to use spark structured streaming with azure event hub example that you have.

Thanks,
Asmath

**Comment by khajaasmath786** [comment]
Hi Sabee,

Sorry, I was working on this request on intemeidate basis. Was about to ask
you question but forgot. How the offsets are stored in this library? do you
have anything specific which stores in db as mentioned in spark programming
guide.

https://spark.apache.org/docs/latest/streaming-kafka-0-10-integration.html

Thanks,
Asmath
