### ISSUE TITLE
Event Hub getting connection aborted frequently

### ISSUE THREAD

**Issue by Adithya-Kanumalla** [Azure/azure-event-hubs-spark#226]
Hi

Issue Description : On starting the spark job I am able to receive the events but after a while I am facing a connection aborted error. 

If I restart the job , I am able to retrieve the events but connection gets aborted again.

Stack Trace attached .
Technical Details: 
- Spark version:2.1
- spark-eventhubs artifactId and version :2.1.6

Thanks
Adithya Kanumalla
[eventhub aborted issue.txt](https://github.com/Azure/azure-event-hubs-spark/files/1674619/eventhub.aborted.issue.txt)

**Comment by sabeegrewal** [comment]
Hey! Sorry for the hold up - I've been a little busier than usual. I'll get back to you later today!

**Comment by sabeegrewal** [comment]
Do you have anymore logs for when this has happened? And how long does the job run before you see this type of error?

**Comment by Adithya-Kanumalla** [comment]
I have seen the job running for 1 min to 30 mins before this happens. 
One key observation completely different to this issue which I have noticed is whenever there is an error in code I can see the connection aborted for sure. I have been able to reproduce this time and again. 
I will share the code and logs for your review tomorrow.
