### ISSUE TITLE
Checkpointing not working with Databricks Structured Streaming?

### ISSUE THREAD

**Issue by seb-dataworks** [Azure/azure-event-hubs-spark#231]
I'm trying to build a Spark Structured Streaming solution in Azure Databricks and reading data from an Azure IoT Hub.
So far this works fine, I can read data and writing this to an Azure SQL Database.
However, checkpointing the event hub inputstream does not seem to work. Every time I start the streaming, it reads from the beginning again.

Used library: azure-eventhubs-databricks_2.11

> val sparkSession = SparkSession.builder().getOrCreate()
> val inputStream = sparkSession.readStream.format("eventhubs").options(eventhubParameters)
>   .load()
> // ... [more code]
> val deviceData = jsoniotTelemetry
                          .filter($"json.deviceId" =!= "").select($"json.deviceId".as("deviceId"),                                 $"json.temperatur".as("temperatur")
                        )
> val writer = new com.microsoft.example.JDBCSink(jdbcUrl, jdbcUsername, jdbcPassword)
>
> val query=deviceData
>   .writeStream
>   .foreach(writer)
>   .outputMode("append")
>   .trigger(ProcessingTime("10 seconds"))  
>   .option("checkpointLocation", "/Ehub/eventhub-checkpoint")
>   .start()

Any idea what I could be missing here? Let me know if you need more details. 
Thanks a lot!

**Comment by sabeegrewal** [comment]
Hey Sebastian, what version of the library are you using?

**Comment by seb-dataworks** [comment]
Databricks Runtime 3.4 | azure-eventhubs-databricks_2.11

**Comment by sabeegrewal** [comment]
Ok, cool - I'm gonna assume you're using `v3.4.0` of the library as well. That version of the library requires a progress directory to be passed in your eventhub parameters. 

We're going to be deprecating this iteration of the library soon. We'll have a `PREVIEW` version of the new library available next week where checkpointing will be more straightforward.

**Comment by seb-dataworks** [comment]
I already have this right now:

> val eventhubParameters = Map[String, String] (
      "eventhubs.policyname" -> "iothubowner",
      "eventhubs.policykey" -> "*************",
      "eventhubs.namespace" -> "**********",
      "eventhubs.name" -> "*******",
      "eventhubs.partition.count" -> "2",
      "eventhubs.consumergroup" -> "databricks",
      "eventhubs.progressTrackingDir" -> "/Ehub/eventhub-progress",
      "eventhubs.maxRate" -> s"1000"
    )

**Comment by sabeegrewal** [comment]
It's possible the checkpointing mechanism is broken - I'm not sure honestly. The reason I took ownership over this repo a couple months ago was there were a number of major issues. I've spent the last couple months rewriting everything. For checkpointing, I'd recommend waiting for the `PREVIEW` next week - the only thing you'll need to do is set a checkpointLocation in Structured Streaming.

**Comment by sabeegrewal** [comment]
I'll leave this issue until the `PREVIEW` is available.

**Comment by seb-dataworks** [comment]
alright, will wait for the new version then. thanks

**Comment by sabeegrewal** [comment]
No worries! Thanks for you understanding - if I had the bandwidth to dig into this more, I would. I have to focus on this new release for now though. 

Thanks again - I'll follow up soon!
