### ISSUE TITLE
Progress Directory Issues

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-event-hubs-spark#232]
### Thanks for filing an issue with us!<br>We appreciate you taking the time to help improve the Event Hubs + Spark Connector :)

**Below are some guidelines when filing an issue. In general, the more detail the better!**
### Bug Report
If this is a bug report, the following information is extremely hepful:
- Actual behavior: Cannot create streamer due to progress directory unable to be created, hooked into or whatever.
- Expected behavior: It just streams my data
- Spark version: Azure Databricks
- spark-eventhubs artifactId and version

#### We're also happy to receive any general feedback, questions, or concerns you might have!

Here is the actual error:
java.io.IOException: Cannot create directory wasbs://CONTAINER@NAME.blob.core.windows.net/streamprogress/Databricks Shell/STUFF-ns-STUFF-STUFF-STUFF-STUFF=sb:/STUFF-ns-STUFF-STUFF-STUFF-STUFF.servicebus.windows.net/;SharedAccessKeyName=STUFF;SharedAccessKey=STUFF through WASB that has colons in the name

spark.conf.set(
  "fs.azure.account.key.NAME.blob.core.windows.net",
  "KEY")
progressDir = "wasbs://CONTAINER@NAME.blob.core.windows.net/streamprogress"

inputStream = spark.readStream.format("eventhubs") \
                .option("eventhubs.policyname", policyName) \
                .option("eventhubs.policykey", policyKey) \
                .option("eventhubs.namespace", eventHubNamespace) \
                .option("eventhubs.name", eventHubName) \
                .option("eventhubs.partition.count", "32") \
                .option("eventhubs.consumergroup", consumerGroup) \
                .option("eventhubs.progressTrackingDir", progressDir) \
                .option("eventhubs.maxRate", "$maxRate") \
                .option("eventhubs.sql.containsProperties", "true") \
                .option("eventhubs.sql.userDefinedKeys", "creationTime,randomUserProperty") \
                .load()

I'm also unclear if this is the minimum set of required options or not.  I really don't care too much about where it stores the progress, so perhaps the resolution is just pointer on how to set it properly

**Comment by drcrook1** [comment]
I tried using this directory as well:
progressDir = "/temp" 

It looks like it is attempting to append my EventHub compatible name to the progress directory.

**Comment by drcrook1** [comment]
I think its working, of course after I report an issue.  I'm connecting to an IoT Hub, and there was confusion over what the name and namespace should be.

**Comment by sabeegrewal** [comment]
Glad it's working. I'm going to close the issue for now. 

Also, we'll be relaunching the library in about a week or two. The most up to date version of the *upcoming* docs are [here](https://github.com/sabeegrewal/azure-event-hubs-spark/tree/spark2.3/docs). They'll be updated fairly regularly until it's merged into `master`.
