### ISSUE TITLE
EventDataSchema: include PartitionID as part of EventDataSchema

### ISSUE THREAD

**Issue by SreeramGarlapati** [Azure/azure-event-hubs-spark#252]
In essence - to make meaning out of the SequenceNumber, Offset etc - EventDataSchema should include partitionId.
This was a popular ask from STORM customers.

**Comment by sabeegrewal** [comment]
cc @sjkwak 

We should discuss this in more detail. I'm inclined to return only what is contained in `EventData`.

**Comment by SreeramGarlapati** [comment]
Sure @sabeegrewal - **I am not sure if `EventDataSchema` is the right place for this though** - but, the key point I want to convey is - while accessing `EventData.offset` and `sequenceNumber` in the Spark query - `PartitionId` should be available :)

- lets say, while consuming events directly using EventHub client sdk - when clients receive data using API `PartitionReceiver.receive()` - `partitionId` is also accessible right there - using - `PartitionReceiver.getPartitionId()`.
`EPH` exposes this on the `IEventProcessor.ProcessEvents(PartitionContext...)`.
as we thought that this info is important for customers to make sense of - SequenceNumber and offset.

**Comment by sabeegrewal** [comment]
I agree that getting offset `X` without knowing the partition isn't too useful. Where would we expose it besides the schema?
