### ISSUE TITLE
PartitionKey always null in stream 

### ISSUE THREAD

**Issue by capitanou** [Azure/azure-event-hubs-spark#308]
Actual behavior:  When reading a stream from an azure eventhub all values in "PartitionKey" are null; however, the stream contains a "PartitionId" that is not included in the output columns.

Expected behavior:  Pass through "PartitionId" in the message or map "PartitionId" to "PartitionKey" in the message

Spark version:  Databricks Runtime 4.0
spark-eventhubs version:  azure-eventhubs-spark_2.11-2.3.1

**Comment by sabeegrewal** [comment]
Hey @capitanou, `PartitionKey` and `PartitionId` are two distinct things. The `PartitionKey` is assigned by the user when the event is initially sent. The key is hashed and used to determine which partition it's sent to. 

The `PartitionId` is separate and is not currently apart of the schema in `2.3.1`. Good news though, I've already added it and it will be in the schema in `2.3.2`. #301 is the PR containing the changes. 

If you don't want to wait, feel free to clone the repo and run `mvn clean package` to get the latest JARs (though it's not as thoroughly tested as `2.3.1`).

**Comment by sabeegrewal** [comment]
Closing the issue - feel free to re-open if you'd like :) I'm also available on our [gitter chat](https://gitter.im/azure-event-hubs-spark/Lobby).
