### ISSUE TITLE
Ensure EntityPath is set in the connection string 

### ISSUE THREAD

**Issue by yokawasa** [Azure/azure-event-hubs-spark#332]
Trying to execute the notebook on [sample](https://docs.azuredatabricks.net/_static/notebooks/structured-streaming-event-hubs-integration.html) but execution failed with the following exception and stream stopped.

> java.util.concurrent.ExecutionException: com.microsoft.azure.eventhubs.AuthorizationFailedException: Put token failed. status-code: 401, status-description: InvalidSignature: The token has an invalid signature. TrackingId:46dada72-3257-4661-984a-67fc53417755, SystemTracker:NoSystemTracker, Timestamp:6/5/2018 12:50:04 PM

the eventhub connection string that I gave to azure-event-hubs-spark is correct.  Actually I tried with a couple of eventhub accounts and their connection strings, however i got the same exception. Of course claims of  their SAS policies include `manage`, not only `send` & `listen`.
Any idea?

Here is the snipped from the sample notebook. 
```
import org.apache.spark.eventhubs._

// Build connection string with the above information
val connectionString = ConnectionStringBuilder("Endpoint=sb://yoichika-eventhub01.servicebus.windows.net/;SharedAccessKeyName=managepolicy;SharedAccessKey=Lg4mzv2qIvnZ+xlam6Gbq/7Whf8ZPMqQN6fRjbqzIhc=")
  .setEventHubName("tweetshub")
  .build

val customEventhubParameters =
  EventHubsConf(connectionString)
  .setMaxEventsPerTrigger(5)

val incomingStream = spark.readStream.format("eventhubs").options(customEventhubParameters.toMap).load()

incomingStream.printSchema

// Sending the incoming stream into the console.
// Data comes in batches!
incomingStream.writeStream.outputMode("append").format("console").option("truncate", false).start().awaitTermination()
```

Here is my environment info:
- Databricks Runtime: `4.0 (includes Apache Spark 2.3.0, Scala 2.11)`
- Spark version: `Apache Spark 2.3.0`
- spark-eventhubs artifactId and version
```
azure-eventhubs-spark_2.11-2.3.1.jar
azure-eventhubs-1.0.1.jar
proton-j-0.25.0.jar
slf4j-api-1.7.25.jar
```

**Comment by sabeegrewal** [comment]
Hey @yokawasa, that's because you don't have an `EntityPath` set in your connection string. 

[This](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/structured-streaming-eventhubs-integration.md#azure-portal) should clear things up. 

This is actually a pretty trivial thing to check in the connector and provide clearer messaging for. I'll update this issue to make it a task to do so :)

**Comment by yokawasa** [comment]
@sabeegrewal  Adding`EntityPath` worked perfect!! thanks alot!!
