### ISSUE TITLE
Limit on number of records being sent ?

### ISSUE THREAD

**Issue by Ycallaer** [Azure/azure-event-hubs-spark#339]
Hi all,
I implemented a pyspark program using the azure event hubs library but when writing data to EventHub I see that the number of records being sent is limited to 350 records per minute. The cluster has 1 throughput unit and is not set to auto inflate. This would allow me to send up to 1MB/sec. 
I am trying to understand where the limitation is coming from.
To limit the dataset I only send 1 field of the entire set as body

Bug Report:

- Actual behavior:
  Dataframe contains 7500 records and has 2 partitions. When the following code is called writing is extremly slow towards EventHub:
```
 connectionString = "Endpoint=sb://Test.servicebus.windows.net/replaytopic;EntityPath=Test;SharedAccessKeyName=USER;SharedAccessKey=KEY"
ehConf = {
  'eventhubs.connectionString' : connectionString
}
data_write = removed_headers_rows.select(removed_headers_rows.incident.alias("body"))

ds = data_write \
  .select("body") \
  .write \
  .format("eventhubs") \
  .options(**ehConf) \
  .save()
```
 In the overview I see that only 350 records per minute are being written (always exactly 350)
Total size of the set trying to write is 1.5 MB
- Expected behavior:
Would have expected a higher throughput
- Spark version:
Databricks 4.1 - Spark 2.3.0 - Scala 2.11
- spark-eventhubs artifactId and version
azure-eventhubs-spark_2.11-2.3.1

**Comment by sabeegrewal** [comment]
Hey @Ycallaer! There's no 350 record limit in the connector. Do you have any other producers sending events to your Event Hub?

**Comment by Ycallaer** [comment]
Hey @sabeegrewal , I had a quick look and figured there is no limit from the implementation but there is a serious performance degradation when running in spark. 
I have also a Java Producer running, which uses the kafka libraries to produce data and I am able to send 140MB in around 30 seconds (same event hub instance)
So I was just wondering where the performance loss could be situated:.

**Comment by sabeegrewal** [comment]
Hey we're handling this in gitter, so I'm going to close the issue! Also, for reference, the resulting work from these conversations can be found here #342
