### ISSUE TITLE
Make IoT Hub system properties available

### ISSUE THREAD

**Issue by hau-mal** [Azure/azure-event-hubs-spark#366]
IoT Hub system properties (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct), e.g. ConnectionDeviceID from messages sent via iot-hub, are not available in properties. Should be available in column properties.

Library: com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.2
Spark 2.3.1, Scala 2.11 (Azure Databricks Runtime 4.2)

**Comment by luzlab** [comment]
+1 on including `deviceID` on messages received from an IoT Hub.

**Comment by sabeegrewal** [comment]
@luzlab @hau-mal hey can you guys let me know: how do you get the deviceID from an `EventData`? I'll do the work on my own too, but if you guys give me a heads up it'll save me a ton of time! I haven't used IoTHub extensively at this point in time.

**Comment by hau-mal** [comment]
@luzlab: Current options from my perspective:
1. put the DeviceID in the message body
2. consume the messages form IoTHub via StreamAnalytics and push them back to EvenHubs

**Comment by luzlab** [comment]
So we're probably going to do #1 (put the deviceId into the body). We've tried #2 (stream analytics job), but now that's additional infrastructure and overhead (1x Stream Analytics job, 1x event hub/namespace). Also, I've been having weird issues with corrupted messages using approach 2 - and now it's a more complicated system to debug.

**Comment by luzlab** [comment]
Here's the streaming analytics query we've been using to move the deviceId into the body of the message.

```
SELECT
    IoTHub.IoTHub.ConnectionDeviceId as deviceId,
    *,
    EventEnqueuedUtcTime as eventEnqueuedTime,
    EventProcessedUtcTime as eventProcessedTime,
    IoTHub.IoTHub.ConnectionDeviceGenerationId as deviceGenerationId,
    IoTHub.IoTHub.CorrelationId as correlationId,
    IoTHub.IoTHub.MessageId as messageId,
    IoTHub.IoTHub.StreamId as streamId
INTO
    [normalized-messages]
FROM
    [IoThub]
```

**Comment by sabeegrewal** [comment]
@luzlab and @hau-mal 

It seems there're some SystemProperties I'm missing - I never grab the IoTHub ones. I need to release `2.3.3` soon and won't be able to include this in the release. I'm happy to release `2.3.4` quickly afterwards with this enhancement! It's on top of my list after the next release is ready.

**Comment by luzlab** [comment]
I noticed 2.3.4 was released recently. Is there any additional documentation on the IoTHub properties?

**Comment by sabeegrewal** [comment]
Hey @luzlab - there was a really sneaky bug in 2.3.3 and I had to release 2.3.4 asap. I didn't have time to include anything besides the fix and some improved exception messaging.
