### ISSUE TITLE
event hub connector cannot manage offset and commits

### ISSUE THREAD

**Issue by stefanofara** [Azure/azure-event-hubs-spark#376]
Hi, on Friday 3rd we experienced the following error

com.microsoft.azure.eventhubs.EventHubException: com.microsoft.azure.eventhubs.impl.AmqpException: The service was unable to process the request

Reading on git Azure/toketi-kafka-connect-iothub#12
we found that

"That container closing error is intermittent and expected when a container closes on one node as part of load balancing on the service or during upgrades. Those failures should not affect the receive functionality and should not block receivers. The container is our messaging container. As part of the load balancing logic containers move from one node to another. Original node closes the container before move. So clients observe this failure until container is available on another node. This should not take more than 20 seconds on average 10 seconds.
Normally this transient exceptions will be handled by our clients retry mechanism: https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-event-hubs-retry-guidelines"

the described scenario is valid for event hub connector also?

after this error we resterd the job and catched the folling one

Assertion failed: received sequence number doesn't match request sequence number

then we deleted the checkpoint folder and file on spark primary storage and now the spark job get events from event hub only at startup then it remains connect but does not receive any events

Now, in the checkpoint location the folder offset conatins only one file and folder commits is missing

We are running spark 2.2
Any idea?

Thanks

**Comment by sabeegrewal** [comment]
When you delete the checkpoint folder, then Spark needs to start from somewhere! By default we'll start from the end of the Event Hubs stream. In general, deleting your checkpoint folder is not advised. 

I'm closing this issue:

The AmqpException is already being tracked in #367.
The "assertion failed" error has been fixed in #364.
