### ISSUE TITLE
com.microsoft.azure.eventhubs.TimeoutException

### ISSUE THREAD

**Issue by sakthig** [Azure/azure-event-hubs-spark#389]
I have two spark jobs running connecting to same eventhub but using different consumer groups..

while one job is running fine. the other job keeps giving this error .. i am sure the connectivity is fine as the other job is running successfully. What could be causing this ?
 
`com.microsoft.azure.eventhubs.TimeoutException: Management request timed out (59999ms), after not receiving response from service. TrackingId: 5c5b9b19f1a34d39872626dee7b94176_G10 	at com.microsoft.azure.eventhubs.impl.ManagementChannel$1.onEvent(ManagementChannel.java:66) 	at com.microsoft.azure.eventhubs.impl.DispatchHandler.onTimerTask(DispatchHandler.java:9) 	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:233) 	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) 	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) 	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) 	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:487) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)`

**Comment by sabeegrewal** [comment]
@sakthig are both jobs connecting to the same Event Hub? 

This exception is from the underlying Java client. Basically, it's saying the service timed out (and therefore it's cancelling the request and throwing an exception). 

@SreeramGarlapati @sjkwak  can you guys take a look?

**Comment by sakthig** [comment]
yes both are to same event hub but different consumer group

**Comment by jpsimen** [comment]
In my case the exception is gone after deleting the checkpoints of the affected streaming query.

**Comment by jpsimen** [comment]
In my pipeline I had split up the streaming DataFrame and after some transformations did a union to have a single result table in the end. This seems to have caused the problem.
Now I changed the implementation in a way that no splitting and union is needed and the exception is gone.

**Comment by sabeegrewal** [comment]
thanks @jpsimen for the info. Still looking into this!

**Comment by sabeegrewal** [comment]
Not able to repro after #394 

Please let me know if you still see this when running from `master`! #394 will be included in `2.3.5` - if you have any questions about that just follow up with me on gitter 👍
