### ISSUE TITLE
Running the streaming code outside of databricks

### ISSUE THREAD

**Issue by saroup** [Azure/azure-event-hubs-spark#390]
Thanks for filing an issue with us! Below are some guidelines when filing an issue. In general, the more detail the better!

Feature Requests: 

- What issue are you trying to solve?
I am trying to run the eventhubs streaming code locally or in the cloud without the use of DataBricks
but I am running into problems when the input stream doesn't contain any data. (The same piece of code give me data in databricks)

**Comment by sabeegrewal** [comment]
Hey @saroup. We try to keep issues confined to specific feature/enhancement tasks or to bug reports. If you'd like help getting started with Event Hubs + Spark, please go to the [gitter chat](https://gitter.im/azure-event-hubs-spark/Lobby).
