### ISSUE TITLE
Freeze executor when # of tasks eq # of cores in the same executor

### ISSUE THREAD

**Issue by murggu** [Azure/azure-event-hubs-spark#393]
We encountered an unexpected behaviour when running Spark's Structured Streaming jobs using the latest (v2.3.4) event-hubs-spark connector.

When the number of tasks is equal to the number of cores in the same executor, that executor get frozen and all the tasks associated to the executor too. Could be this potential issue related to CachedReceivers?

We need to restart the cluster to skip the freeze state.

**Comment by sabeegrewal** [comment]
Just an FYI for everyone - we're investigating the issue!

**Comment by sabeegrewal** [comment]
Not able to repro after #394
