### ISSUE TITLE
Data source com.databricks.spark.sqldw does not support streamed writing

### ISSUE THREAD

**Issue by ManjunathGuntha** [Azure/azure-event-hubs-spark#400]
In databricks, I am reading data from eventhub and  trying to write Streaming data to SQL DW : 

Df.writeStream
  .format("com.databricks.spark.sqldw")
  .option("url", s"<value>")
  .option("forwardSparkAzureStorageCredentials", "true")
  .option("dbTable", "< table name>")
  .option("checkpointLocation", "checkpoint_location")
  .start()

but i am getting the below error:
java.lang.UnsupportedOperationException: Data source com.databricks.spark.sqldw does not support streamed writing

Can you please look into this issue?

**Comment by sabeegrewal** [comment]
@ManjunathGuntha you're asking a question about `sqldw` - that's nothing something supported on this repo. It sounds like the sink only works in batch scenarios, but you need to contact the owners of `sqldw` to be sure.
