### ISSUE TITLE
Remove the log of configuration value when it is overwritten

### ISSUE THREAD

**Issue by bryanchen-d** [Azure/azure-event-hubs-spark#403]
- What issue are you trying to solve?
Spark job log contains connection string including the access key, for example:

18/10/16 04:26:50 WARN EventHubsConf: eventhubs.connectionstring has already been set to Endpoint=sb://***.servicebus.windows.net;EntityPath=t***;SharedAccessKeyName=***;SharedAccessKey=***. Overwriting with Endpoint=sb://***.servicebus.windows.net;EntityPath=***;SharedAccessKeyName=***;SharedAccessKey=***

we want to remove the raw value of connection string in this log in case of leaking the secret keys.

- How do you want to solve it? 
The log comes from 
https://github.com/Azure/azure-event-hubs-spark/blob/master/core/src/main/scala/org/apache/spark/eventhubs/EventHubsConf.scala
around line 68:
    if (self.get(lowerKey).isDefined) {
      logWarning(s"$key has already been set to ${self.get(key).get}. Overwriting with $value")
    }

we may update it to logWarning(s"$key has already been set.")

Also it would be better to see if the value is the same first, and skip overwriting if the new value is the same as the old.

**Comment by sabeegrewal** [comment]
Bryan, for now, this will work:

```scala
newString = "FOO"
if (ehConf.connectionString != newString) { ehConf.setConnectionString(newString) } 
```

Thanks for putting this in! I agree - the key shouldn't be printed.

**Comment by bryanchen-d** [comment]
Thanks @sabeegrewal  for the quick response!

However I don't know how this is called, what I do is just putting the connection info into a EventHubsConf and call EventHubsUtils.createDirectStream() to start streaming, it seems somewhere inside is setting the connection without checking if it is the same.

**Comment by sjkwak** [comment]
This issue is being address by pull request #406

**Comment by bryanchen-d** [comment]
Hi, the commit just add a check but it could still print out the connection string into log, which would be a security issue in our scenario. can we also update the log from 
```
logWarning(s"$key has already been set to ${self.get(key).get}. Overwriting with $value")
```
to
```
logWarning(s"$key has already been set.")
```

**Comment by bryanchen-d** [comment]
How do I reactivate this?
