### ISSUE TITLE
Table to EventHub

### ISSUE THREAD

**Issue by eaidland** [Azure/azure-event-hubs-spark#405]
Hi!

I'm reading some csv files from a datalake (mounted) and creating a temp view "X" columns (time, value, name). Now I want to to send that dataframe to an EventHub. I've created a Python function to do this, but I can't figure out how to convert the dataframe to "body".  What's the trick here? Why can't I just send in the dataframe?

```
write_to_eventhub_batch(df)

def write_to_eventhub_batch(df):
  ds = df \
  .select("body") \
  .write \
  .format("eventhubs") \
  .options(**ehConf) \
  .save()
```

**Comment by sabeegrewal** [comment]
You are sending the dataframe - specifically, each row in the 'body' column is turned into an event and sent to EventHubs. That's how we know what data you want to send. 

So, before you write to EventHubs, your event payload needs to be in a column named 'body'. You can do this with the withColumnRenamed API. More info is [here](https://spark.apache.org/docs/latest/api/java/index.html?org/apache/spark/sql/Dataset.html). 

There're additional APIs available in Spark to combine columns as well.
