### ISSUE TITLE
EventHubsForeachWriter example not working

### ISSUE THREAD

**Issue by Ilanak** [Azure/azure-event-hubs-spark#414]
I'm trying to use EventHubsForeachWriter, as showed [here](https://github.com/Azure/azure-event-hubs-spark/blob/1c198ba39a612afc08dca2646a1584570295ae1b/docs/structured-streaming-eventhubs-integration.md#foreachwriter):

val ehConf = EventHubsConf("YOUR_CONNECTION_STRING") 
val writer = EventHubsForeachWriter(ehConf)

val query =
  streamingSelectDF
    .writeStream
    .foreach(writer)
    .outputMode("update")
    .trigger(ProcessingTime("25 seconds"))
    .start()
but i'm getting an exception:

notebook:22: error: type mismatch;
 found   : org.apache.spark.sql.eventhubs.EventHubsForeachWriter
 required: org.apache.spark.sql.ForeachWriter[org.apache.spark.sql.Row]
    .foreach(writer)

**Comment by sjkwak** [comment]
Hi @Ilanak, please try streamingSelectDF.selectExpr("cast(body as string)").as[String] and let us know if you still see the issue.

**Comment by KunwarAkanksha** [comment]
I am getting the same problem , selectExpr("cast(body as string)").as[String]  still didnt solved it
