### ISSUE TITLE
Spark streaming (HDInsight) connect to IoT Hub: Failed to find data source: eventhubs

### ISSUE THREAD

**Issue by ganges-morekonda** [Azure/azure-event-hubs-spark#418]
I'm trying to stream date to Spark HDInsight from IoT Hub using EventHub compatible endpoint. I'm running my setup in Jupyter Notebook.

**In [1]:** spark.version
SparkSession available as 'spark'.
'2.2.0.2.6.3.61-4'

**in[2]:** ehConf = { 'eventhubs.connectionString' : eventHubNSConnStr }
          df = spark.readStream.format('eventhubs').options(**ehConf).load()

An error occurred while calling o196.load.
: java.lang.ClassNotFoundException: Failed to find data source: eventhubs. Please find packages at http://spark.apache.org/third-party-projects.html

Any help will be much appreciated!

Thanks,
ganges....

**Comment by sabeegrewal** [comment]
Hey ganges, this is because the the `azure-eventhubs-spark` package can't be found in your runtime environment. You should search how to include Maven packages in Spark HDInsight. There're certainly tutorials that walk through the process.
