### ISSUE TITLE
connection time out with event hub when using spark streaming which connect with event hub 

### ISSUE THREAD

**Issue by rs10615** [Azure/azure-event-hubs-spark#422]
[spark version 2.2.1 and sdk version  azure-eventhubs-spark_2.11  ,2.2.7 after running for 3-4 hour i found below exception which is keeping occurring for every day in production. 
I am using following code for stream over spark 
---------------------------------------------------------------------------------------------------------------
class EventConnector() {

  val logger = Logger.getLogger(this.getClass);

  /**
   * This method will make the connection with the azure event hub
   * and return the object connection String.
   * @return connStr : object of String
   */
  def getConnection(): String = {

    logger.info("Connection need to be established with event hub")

    val eventHubNSConnStr = Constants.eventHubNSConnStr;
    val eventHubName = Constants.eventHubName

    val connStr = ConnectionStringBuilder(eventHubNSConnStr).setOperationTimeout(Duration.ofSeconds(1800000)).setEventHubName(eventHubName).build;

    logger.info("Connection established with event hub");

    return connStr
---------------------------------------------------------------------------------------------------------------
 var maxEventTrigger: Long = Constants.maxEventTrigger.toLong;
    val customEventhubParameters = EventHubsConf(connStr).setMaxEventsPerTrigger(maxEventTrigger);
    val incomingStream = spark.readStream.format("eventhubs").options(customEventhubParameters.toMap).load();
    logger.info("Data has been fetched from event hub successfully");
    val messages = incomingStream.withColumn("Offset", $"offset".cast(LongType)).withColumn("Time (readable)", $"enqueuedTime".cast(TimestampType)).withColumn("Timestamp", $"enqueuedTime".cast(LongType)).withColumn("Body", $"body".cast(StringType)).select("Offset", "Time (readable)", "Timestamp", "Body")

    implicit val formats = DefaultFormats;
------------------------------------------------------------------------------------------

19/01/09 20:00:22 WARN ConnectionHandler: onTransportError: hostname[edgeeventhub.servicebus.windows.net:5671], error[Connection timed out]
19/01/09 20:00:22 WARN MessagingFactory: onConnectionError: messagingFactory[MessagingFactory9c61b3], hostname[edgeeventhub.servicebus.windows.net], error[Connection timed out]
19/01/09 20:00:22 WARN MessagingFactory: onConnectionError: messagingFactory[MessagingFactory9c61b3], hostname[edgeeventhub.servicebus.windows.net], closing link [cbs:sender]
19/01/09 20:00:22 WARN MessagingFactory: onConnectionError: messagingFactory[MessagingFactory9c61b3], hostname[edgeeventhub.servicebus.windows.net], closing link [cbs:receiver]
19/01/09 20:00:22 WARN MessagingFactory: onConnectionError: messagingFactory[MessagingFactory9c61b3], hostname[edgeeventhub.servicebus.windows.net], closing link [c2e9a4_27f_G25_1547061129961]
19/01/09 20:00:22 WARN MessagingFactory: onConnectionError: messagingFactory[MessagingFactory9c61b3], hostname[edgeeventhub.servicebus.windows.net], closing current connection
19/01/09 20:00:22 INFO BaseLinkHandler: processOnClose linkName[cbs:sender], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 INFO BaseLinkHandler: processOnClose linkName[cbs:receiver], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 INFO MessageReceiver: clientId[PartitionReceiverImpl81d869-InternalReceiver], path[edgeeventhub/ConsumerGroups/$Default/Partitions/20], linkName[c2e9a4_27f_G25_1547061129961], tokenRenewalFailure[Connection timed out]
19/01/09 20:00:22 INFO BaseLinkHandler: processOnClose linkName[c2e9a4_27f_G25_1547061129961], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 WARN MessageReceiver: clientId[PartitionReceiverImpl81d869-InternalReceiver], receiverPath[edgeeventhub/ConsumerGroups/$Default/Partitions/20], linkName[c2e9a4_27f_G25_1547061129961], onError: com.microsoft.azure.eventhubs.EventHubException: Connection timed out
19/01/09 20:00:22 INFO BaseLinkHandler: onLinkLocalClose linkName[cbs:sender], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 INFO BaseLinkHandler: closeSession for linkName[cbs:sender], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 INFO BaseLinkHandler: onLinkLocalClose linkName[cbs:receiver], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 INFO BaseLinkHandler: onLinkLocalClose linkName[c2e9a4_27f_G25_1547061129961], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 INFO BaseLinkHandler: closeSession for linkName[c2e9a4_27f_G25_1547061129961], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 INFO ConnectionHandler: onConnectionLocalClose: hostname[edgeeventhub.servicebus.windows.net:5671], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:22 INFO ConnectionHandler: onConnectionUnbound: hostname[edgeeventhub.servicebus.windows.net:5671], state[CLOSED], remoteState[ACTIVE]
19/01/09 20:00:22 INFO SessionHandler: onSessionLocalClose entityName[cbs-session], condition[Error{condition=proton:io, description='Connection timed out', info=null}]
19/01/09 20:00:22 INFO SessionHandler: onSessionLocalClose entityName[edgeeventhub/ConsumerGroups/$Default/Partitions/20], condition[Error{condition=proton:io, description='Connection timed out', info=null}]
19/01/09 20:00:22 INFO SessionHandler: onSessionFinal entityName[cbs-session], condition[proton:io], description[Connection timed out]
19/01/09 20:00:22 INFO SessionHandler: onSessionFinal entityName[edgeeventhub/ConsumerGroups/$Default/Partitions/20], condition[proton:io], description[Connection timed out]
19/01/09 20:00:22 INFO ConnectionHandler: onConnectionFinal: hostname[edgeeventhub.servicebus.windows.net:5671], errorCondition[proton:io], errorDescription[Connection timed out]
19/01/09 20:00:23 INFO MessageReceiver: clientId[PartitionReceiverImpl81d869-InternalReceiver], path[edgeeventhub/ConsumerGroups/$Default/Partitions/20], operationTimeout[PT5M], creating a receive link
19/01/09 20:00:23 INFO ConnectionHandler: onConnectionInit hostname[edgeeventhub.servicebus.windows.net]
19/01/09 20:00:23 INFO SessionHandler: onSessionLocalOpen entityName[cbs-session], condition[Error{condition=null, description='null', info=null}]
19/01/09 20:00:23 INFO SendLinkHandler: onLinkLocalOpen linkName[cbs:sender], localTarget[Target{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}]
19/01/09 20:00:23 INFO ReceiveLinkHandler: onLinkLocalOpen linkName[cbs:receiver], localSource[Source{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}]
19/01/09 20:00:23 INFO ConnectionHandler: onConnectionLocalOpen: hostname[edgeeventhub.servicebus.windows.net:5671], errorCondition[null], errorDescription[null]
19/01/09 20:00:23 INFO ConnectionHandler: onConnectionBound hostname[edgeeventhub.servicebus.windows.net]
19/01/09 20:00:23 INFO ConnectionHandler: onConnectionRemoteOpen: hostname[edgeeventhub.servicebus.windows.net:5671], remoteContainer[02cc242dab5548aca4721d80a18640ee_G12]
19/01/09 20:00:23 INFO SessionHandler: onSessionRemoteOpen entityName[cbs-session], sessionIncCapacity[0], sessionOutgoingWindow[2147483647]
19/01/09 20:00:23 INFO SendLinkHandler: onLinkRemoteOpen linkName[cbs:sender], remoteTarget[Target{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}]
19/01/09 20:00:23 INFO ReceiveLinkHandler: onLinkRemoteOpen linkName[cbs:receiver], remoteSource[Source{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}]
19/01/09 20:00:23 INFO SessionHandler: onSessionLocalOpen entityName[edgeeventhub/ConsumerGroups/$Default/Partitions/20], condition[Error{condition=null, description='null', info=null}]
19/01/09 20:00:23 INFO SessionHandler: onSessionRemoteOpen entityName[edgeeventhub/ConsumerGroups/$Default/Partitions/20], sessionIncCapacity[0], sessionOutgoingWindow[2147483647]
19/01/09 20:00:23 INFO PartitionReceiverImpl: receiverPath[edgeeventhub/ConsumerGroups/$Default/Partitions/20], action[createReceiveLink], offset[null], sequenceNumber[16540], enqueuedTime[null], inclusiveFlag[true]
19/01/09 20:00:23 INFO ReceiveLinkHandler: onLinkLocalOpen linkName[62dec2_0ee_G12_1547064023250], localSource[Source{address='edgeeventhub/ConsumerGroups/$Default/Partitions/20', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter={apache.org:selector-filter:string=UnknownDescribedType{descriptor=apache.org:selector-filter:string, described=amqp.annotation.x-opt-offset > '85900897208'}}, defaultOutcome=null, outcomes=null, capabilities=null}]
19/01/09 20:00:23 INFO ReceiveLinkHandler: onLinkRemoteOpen linkName[62dec2_0ee_G12_1547064023250], remoteSource[Source{address='edgeeventhub/ConsumerGroups/$Default/Partitions/20', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter={apache.org:selector-filter:string=org.apache.qpid.proton.codec.DecoderImpl$UnknownDescribedType@3f2f21a3}, defaultOutcome=null, outcomes=null, capabilities=null}]
19/01/09 20:00:23 INFO MessageReceiver: onOpenComplete - clientId[PartitionReceiverImpl81d869-InternalReceiver], receiverPath[edgeeventhub/ConsumerGroups/$Default/Partitions/20], linkName[62dec2_0ee_G12_1547064023250], updated-link-credit[500], sentCredits[500]
19/01/09 20:01:00 INFO CrowdCountJob: Crowd count job now has been scheduled.
19/01/09 20:01:00 INFO RedisConnector: Connection need to be established with redis.
19/01/09 20:01:00 INFO DemographicJob: Demographics job has been scheduled.
19/01/09 20:01:00 INFO RedisConnector: Connection need to be established with redis.
19/01/09 20:01:00 INFO StoreJob: Store Count job now has been scheduled 

](url)

**Comment by sjkwak** [comment]
@rs10615 traces show that connection was timeout and then it was recreated and the underlying receiver was opened successfully. So, it looks there was a transient failure and recovered. Was your spark job faulted because of the error?

**Comment by rs10615** [comment]
actually after this exception i found that no more streaming happen on spark and data has been stopped receiving from event hub ,if you want more log to analyze the same i can provide you .
Questions:
1)is there any problem when multiple spark job subscribe the same event hub end point 
2)when there is more traffic on event hub ,we have pub sub model like multiple device publishing data on same event hub and through spark streaming we are processing data and multiple scheduler getting the same data from redis cache and dumping the data into database

**Comment by rs10615** [comment]
> @rs10615 traces show that connection was timeout and then it was recreated and the underlying receiver was opened successfully. So, it looks there was a transient failure and recovered. Was your spark job faulted because of the error?

actually after this exception i found that no more streaming happen on spark and data has been stopped receiving from event hub ,if you want more log to analyze the same i can provide you .
Questions:
1)is there any problem when multiple spark job subscribe the same event hub end point
2)when there is more traffic on event hub ,we have pub sub model like multiple device publishing data on same event hub and through spark streaming we are processing data and multiple scheduler getting the same data from redis cache and dumping the data into database

**Comment by sjkwak** [comment]
In case of multiple spark jobs, you would need to use a different consumer group per each job to make sure receivers are not interfering with each other.

**Comment by rs10615** [comment]
can you just help me with code how define multiple consumer group ? and connect with spark streaming using different consumer group ?

**Comment by rs10615** [comment]
> can you just help me with code how define multiple consumer group ? and connect with spark streaming using different consumer group ?

**Comment by sjkwak** [comment]
Hi @rs10615 you can use setConsumerGroup API in the EventHubsConf class. Please note that you will need to create a consumer group if it doesn't exist.
