### ISSUE TITLE
Writing to event hub takes long

### ISSUE THREAD

**Issue by chris-rs** [Azure/azure-event-hubs-spark#433]
I created a Spark script which processes sensordata. The data streams in at rates of 1000s of records a second.
Spark receives these records in batch from event hub, processes these and writes the results on a different Event Hub. The processing of the data takes a couple of seconds (at most) but it seems that sinking these results to Event Hub takes long (2 min. for 10.000 records).
When I skip Event Hub sink and just save the records to storage Spark takes a couple of seconds for a single batch, but the batch duration increases dramatically when Spark writes to Event Hub as well.

For clarity my Event hub writer code below
```
val ehConf = EventHubsConf(connection getOrElse "")
       .setMaxEventsPerTrigger(5000)

def saveFlows(records: DataFrame) = {
	records
		.selectExpr("CAST(usr AS STRING) AS partitionKey", "to_json(struct(usr, env, hr, hrv, tsToLong(ts) AS ts)) AS body")
	        .write
	        .format("eventhubs")
	        .options(ehConf.toMap)  
	        .save()
}
```
I throttled the number of TU in Azure portal (to 10) but it seems that this does not effect the batch duration. Also tried the setting ``setMaxEventsPerTrigger`` but that shortens the duration neither.
I partition the data per user.

Do I miss some setting, cause I cannot imagine Event Hub cannot manage this throughput?
I'm using EventHub connector 2.3.6 with Spark 2.4.

Regards

**Comment by duydao** [comment]
The EventHubsForeachWriter should improve the performance, however it seems like the current version is not compatible to the latest Version of databricks:

 found   : org.apache.spark.sql.eventhubs.EventHubsForeachWriter
 required: org.apache.spark.sql.ForeachWriter[org.apache.spark.sql.Row]

**Comment by duydao** [comment]
See #414 for a solution of the EventHubsForeachWriter issue

**Comment by chris-rs** [comment]
@duydao Using the EventHubsForeachWriter is indeed much faster. The problem is that I use a partitionkey since records within a partition should maintain order. The foreachwriter is round-robin so all records arrive out of order which makes it useless for me, since a second Spark process reads the hub and can only perform correct analysis if the data arrives in order.

**Comment by hustlestar** [comment]
Is there any way to control writing to Event Hub from PySpark? Writing 650k to Event Hub with 10 TU sometimes takes more then 1 hour. I can see that Spark stucks at some point (after 150k messages) and then doesn't perform any writes. Please advise
