### ISSUE TITLE
java.lang.NoClassDefFoundError at org.apache.spark.eventhubs.EventPosition

### ISSUE THREAD

**Issue by jojinmp** [Azure/azure-event-hubs-spark#440]
My configurations are.

Spark: 2.4.0

Scala: 2.12

Event hub connector:
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-eventhubs-spark_2.11</artifactId>
            <version>2.3.10</version>
        </dependency>

I am getting below error while trying to stream from event hub, Please help.

java.lang.NoClassDefFoundError: scala/Product$class
	at org.apache.spark.eventhubs.EventPosition.<init>(EventPosition.scala:35)
	at org.apache.spark.eventhubs.EventPosition$.apply(EventPosition.scala:31)
	at org.apache.spark.eventhubs.EventPosition$.fromEndOfStream(EventPosition.scala:116)
	at org.apache.spark.eventhubs.package$.<init>(package.scala:36)
	at org.apache.spark.eventhubs.package$.<clinit>(package.scala)
	at org.apache.spark.eventhubs.EventPosition$.fromEndOfStream(EventPosition.scala:116)
	at sample.EventHubStreaming$.main(EventHubStreaming.scala:13)
	at sample.EventHubStreaming.main(EventHubStreaming.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by sjkwak** [comment]
Hi @jojinmp the library is compiled against Scala 2.11. So, please try Scala 2.11.

**Comment by jojinmp** [comment]
Thanks @sjkwak , While using 2.4 Intellij asking me to use scala 2.12 SDK.

So I used below configuration to try with 2.11

Spark 2.3.0

Scala 2.11

Event hub connector:

com.microsoft.azure
azure-eventhubs-spark_2.11
2.3.10

But am not even able to compile as its throwing multiple issues.

1. val connectionString = ConnectionStringBuilder("Connectionstring_with_entitypath").build
     Is giving error "cannot resolve overloaded method 'ConnectionStringBuilder' "

2. val eventhubs = spark.readStream
      .format("eventhubs")
      .options(eventHubsConf.toMap)
      .load()
      Is having error at options saying "Type mismatch"

And multiple related issues, I am able to run the same code in databricks Jupiter notbook without any hustle. It might be a simple step/configuration missing here, But I am failing miserably to figure out what it is, even after spending around two weeks. 

I want to just hit eventhub and read Json payload using spark structured streaming, I have invested quite bit time on the same and still no luck. I am able to setup the same and even more in Jupiter notebook with ease by following the steps provided in this git as well as in Databricks documentation. But we need to configure in IntelliJ for further development. 

If you have a sample spark scala  Maven/Sbt project which hit eventhub and retrieve events using Spark structured streaming, Could you please add it to your docs/code sample? It would be a great for me as well as fellow googlers who wants setup the same in their production environment. So that we could just load the sample and could concentrate on actual development/tasks.

Thanks in advance!

**Comment by sjkwak** [comment]
Hi @jojinmp, are you using SBT? Here is a sample for build.sbt file. Can you try it?

name := "test"
version := "0.1"
scalaVersion := "2.11.8"

// https://mvnrepository.com/artifact/org.apache.spark/spark-core
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.3.2"

//https://mvnrepository.com/artifact/org.apache.spark/spark-streaming
libraryDependencies += "org.apache.spark" %% "spark-streaming" % "2.3.2"

//https://mvnrepository.com/artifact/org.apache.spark/spark-streaming
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.3.2"

libraryDependencies += "com.microsoft.azure" %% "azure-eventhubs-spark" % "2.3.10"

libraryDependencies += "com.microsoft.azure" % "azure-eventhubs" % "2.3.0"

**Comment by jojinmp** [comment]
Great..!! Thanks, Its working.

If possible could you please share the Spark 2.4.x configuration as well? As its a new project we would like to start with latest version of spark. Does the below settings should work?

Thank you once again,,:)

name := "test"
version := "0.1"
scalaVersion := "2.11.8"

// https://mvnrepository.com/artifact/org.apache.spark/spark-core
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.4.0"

//https://mvnrepository.com/artifact/org.apache.spark/spark-streaming
libraryDependencies += "org.apache.spark" %% "spark-streaming" % "2.4.0"

//https://mvnrepository.com/artifact/org.apache.spark/spark-streaming
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.0"

libraryDependencies += "com.microsoft.azure" %% "azure-eventhubs-spark" % "2.3.10"

libraryDependencies += "com.microsoft.azure" % "azure-eventhubs" % "2.3.0"

**Comment by sjkwak** [comment]
Yes, 2.4.0 should work. Please note that Azure Databricks runtime version 5.x supports Spark version 2.4.

**Comment by dlpkmr98** [comment]
facing same issue with Maven..

[ERROR] error: bad symbolic reference to org.apache.http.annotation.Experimental encountered in class file 'EventHubsConf.class'.
[INFO] Cannot access type Experimental in package org.apache.http.annotation. The current classpath may be
[INFO] missing a definition for org.apache.http.annotation.Experimental, or EventHubsConf.class may have been compiled against a version that's
[INFO] incompatible with the one found on the current classpath.
[ERROR] one error found

**Comment by dlpkmr98** [comment]
lib used..

<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<spark.version>2.4.3</spark.version>
		<scalatest.version>3.2.0-M1</scalatest.version>
		<scala.version>2.11</scala.version>
		
	</properties>

==========================
<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-streaming_${scala.version}</artifactId>
			<version>${spark.version}</version>			
		</dependency>

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-eventhubs-spark_${scala.version}</artifactId>
			<version>2.3.10</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-eventhubs</artifactId>
			<version>2.3.0</version>
		</dependency>
