### ISSUE TITLE
Incorrect filtering by enqueuedTime

### ISSUE THREAD

**Issue by FurcyPin** [Azure/azure-event-hubs-spark#444]
## Bug Report:
Event Hub's filtering by startingPosition and endingPosition seem to not work correctly and return events with EnqueuedTime that are out of bounds.

### Actual behavior

By running the following code sample (credentials redacted)
```
val spark = SparkSession.builder().appName("AbrisPoc").master("local[2]").config("spark.sql.session.timeZone", "UTC").getOrCreate()

  val df =
    spark.read.format("eventhubs").option(
      "eventhubs.connectionString", "Endpoint=amqps://XXXXXXXXXX.servicebus.windows.net/XXXXXXXXXX;EntityPath=XXXXXXXXXXXXXXXXXXX;etc."
    ).option(
      "eventhubs.startingPosition", """{"offset": null, "seqNo": -1, "enqueuedTime": "2019-04-26T00:00:00.000000Z", "isInclusive": true}"""
    ).option(
      "eventhubs.endingPosition", """{"offset": null, "seqNo": -1, "enqueuedTime": "2019-04-26T23:59:59.999999Z", "isInclusive": true}"""
    ).load()
  df.selectExpr("""MAX(EnqueuedTime)""").show(10, truncate = false)
```
We get the following result
```
  +-----------------------+
  |max(EnqueuedTime)      |
  +-----------------------+
  |2019-04-27 00:13:00.889|
  +-----------------------+
```
which is outside the specified interval of `2019-04-26T00:00:00.000000Z` to `2019-04-26T23:59:59.999999Z`

### Expected behavior
All the returned events should have an EnqueuedTime between the specified bounds.

### Spark version : 
2.3.3

### spark-eventhubs artifactId and version: 
from my sbt project:
```
libraryDependencies += "com.microsoft.azure" % "azure-eventhubs-spark_2.11" % "2.3.9"
libraryDependencies += "com.microsoft.azure" % "azure-eventhubs" % "2.2.0"
```

**Comment by Molotch** [comment]
We're having what probably is the same issue but the other way around. On some occasions a single message in the last second of the batch fetched is not in the result set even though the message is in the result set of the capture function. We're on Spark 2.4.3 and connector version 2.3.13.

I would suggest everyone make sure they fetch events with a slight margin and filter in Spark instead of in the connector. For us this has only been an issue with the end time, the start time seems to work fine.

**Comment by nyaghma** [comment]
Please upgrade to the current version (2.3.14.1) and let us know if you still see the problem.

**Comment by nyaghma** [comment]
I'm closing this issue now. Please reopen if you see the same problem using the current version.

**Comment by sandeep8530** [comment]
Hi,

I upgraded to current version 2.3.14.1 and i still see this issue

'eventhubs.startingPosition': '{"offset": null, "seqNo": -1, "enqueuedTime": "2020-04-07T01:05:05.662231Z", "isInclusive": true}',
 'eventhubs.endingPosition': '{"offset": null, "seqNo": -1, "enqueuedTime": "2020-04-07T01:15:05.662185Z", "isInclusive": true}'}

But fetched results are between 
2020-04-07 01:16:07.459 & 
2020-04-07 01:26:06.953

**Comment by nyaghma** [comment]
Can you share the code snippet where you set the start and end position? Are you using EventHubsConf as suggested [here ](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/spark-streaming-eventhubs-integration.md#eventhubsconf)?

**Comment by sandeep8530** [comment]
Hi,

Thanks for quick reply! Below is the code. This is in pyspark. Please let me know if you need any other info.

ehConf = {'eventhubs.connectionString' : connectionString}

# Start from beginning of stream
startOffset = "-1"
startTime = "2020-04-07T01:05:05.662231Z"
endTime = "2020-04-07T01:15:05.662185Z"


startingEventPosition = {
  "offset": None,  
  "seqNo": -1,            #not in use
  "enqueuedTime": startTime,   
  "isInclusive": True
}

endingEventPosition = {
  "offset": None,           #not in use
  "seqNo": -1,              #not in use
  "enqueuedTime": endTime,
  "isInclusive": True
}

# Put the positions into the Event Hub config dictionary
ehConf["eventhubs.startingPosition"] = json.dumps(startingEventPosition)
ehConf["eventhubs.endingPosition"] = json.dumps(endingEventPosition)

df = spark.read.format("eventhubs").options(**ehConf).load()

**Comment by sandeep8530** [comment]
Hi,

Just want to check if you have any update on this?

**Comment by nyaghma** [comment]
@sandeep8530 I got distracted by other work. I'll look into this further later today.

**Comment by guoch** [comment]
May I know the real meaning of the endingEventPosition  ?  I also had the same issue using the enqueuedTime, so I tried to test using the offset directly.
My eventhub had two partitions and my code snippet is as below.  I am using the latest SDK version 


`val positions = Map(
  new NameAndPartition("twitter", 0) -> EventPosition.fromOffset("700085393488"),
  new NameAndPartition("twitter", 1) -> EventPosition.fromOffset("700085423280")  
)


val positions_end = Map(
  new NameAndPartition("twitter", 0) -> EventPosition.fromOffset("700085395344"),
  new NameAndPartition("twitter", 1) -> EventPosition.fromOffset("700085424960")
)



val ehConf = EventHubsConf(connectionString)
  .setStartingPositions(positions)
  .setEndingPositions(positions_end)
  .setMaxEventsPerTrigger(10)


val offsetStreaming = spark.readStream.format("eventhubs").options(ehConf.toMap).load()

    val message_offset =
      offsetStreaming
      .withColumn("Offset", $"offset".cast(LongType))
      .withColumn("Body", $"body".cast(StringType))`

In my partition 1,  the  endoffset is 700085424960. However, I see the 700085436536 in output, which is exceeding the defined end offset.
![Capture](https://user-images.githubusercontent.com/2719716/82776378-4b523200-9e7d-11ea-9c68-0b0d0dc55cbd.PNG)

**Comment by sandeep8530** [comment]
@nyaghma , Thanks a lot for looking into it. Yes, It is working fine, If i use only 3 digits millisecond precision. 

However in this documentation (https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/PySpark/structured-streaming-pyspark.md) below code is used in the filter which gives 6 digits. Appreciate, if you could update this to avoid any further confusion.

endTime = dt.now().strftime("%Y-%m-%dT%H:%M:%S.%fZ")

**Comment by FurcyPin** [comment]
Hi, sorry for reopening the subject but I have a small question:

I understand that the bug is that passing a six-digit number of milliseconds causes an overflow which caused the bounds to be wrong, and that users should use .999 instead of .999999 for instance.

My question is: what is the time precision used by EventHub ? Is it millisecond or nanosecond ?

What I would like to be sure of is that if I query each day events between `"00:00:00.000"` and `"23:59:59.999"`, is there a possibility to miss an event with a timestamp like "23:59:59.9995"?

**Comment by nyaghma** [comment]
@guoch endingPosition / endingPositions determine the ending position of a batch query. Sine in a streaming query there is no end position, this value would be simply ignored even if it's been set in the client code. If you want to read events to a certain point use batch query instead of streaming query.

**Comment by nyaghma** [comment]
@FurcyPin Eventhubs uses nanosecond precision. This millisecond precision is specific to the python client. If you write your client code using Scala you can use the nanosecond precision.

**Comment by FurcyPin** [comment]
@nyaghma thank you for your answer.
I'm sorry but I don't understand what you mean by "This millisecond precision is specific to the python client"
As far as I can tell the python datetime library handles nanosecond precision perfectly, and then, when we call the python API like this, all it does it pass the options to Scala as strings.

```
conf = {
    "eventhubs.connectionString": "Endpoint=amqps://XXXXXXXXXX.servicebus.windows.net/XXXXXXXXXX;EntityPath=XXXXXXXXXXXXXXXXXXX;etc.",
    "eventhubs.startingPosition": """{"offset": null, "seqNo": -1, "enqueuedTime": "2019-04-26T00:00:00.000000Z", "isInclusive": true}""",
    "eventhubs.endingPosition": """{"offset": null, "seqNo": -1, "enqueuedTime": "2019-04-26T23:59:59.999999Z", "isInclusive": true}"""
}

df = spark.read.format("eventhubs").options(**conf).load()
```

So my guess is that when Scala parses these dates it uses Java's SimpleDateFormat which is bugged and interprets nanoseconds as milliseconds.

**Comment by guoch** [comment]
> endingPosition / endingPositions determine the ending position of a batch query. Sine in a streaming query there is no end position, this value would be simply ignored even if it's been set in the client code. If you want to read events to a certain point use batch query instead of streaming query.

Hi @nyaghma  Thank you a lot for this reply and confirmation. If possible, I would suggest you could add the comment here as well https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/structured-streaming-eventhubs-integration.md#eventhubsconf in the end position, so it may help others who had the similar question like me.
