### ISSUE TITLE
Question on mapping to Spark Streaming

### ISSUE THREAD

**Issue by rsethur** [Azure/azure-event-hubs-spark#452]
Thank you for the kind support.
Question: If we have a event hub with 4 partitions and huge number of events in each, how many concurrent access readers will read from Spark Streaming? Will there be one executor per partition?

Also can you please explain what is DefaultThreadPoolSize ?

Any best practices would be appreciated.

**Comment by nyaghma** [comment]
The library creates a receiver per partition-cosumerGroup combo to read events from each partition, regardless of the number of events in partitions. Therefore, for an Eventhubs instance with 4 partitions the stream will create 4 concurrent readers. 
Spark creates a task to read from each partition and decides to dispatch it to which executor node. The number of executor nodes is being assigned when you start the cluster. The library creates an [ExecutorService](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledExecutorService.html) on each executor node and uses the threadPoolSize to determine the number of threads for the ExecutorService.
