### ISSUE TITLE
Kafka key missing

### ISSUE THREAD

**Issue by hau-mal** [Azure/azure-event-hubs-spark#455]
I am writing key value pairs to an EventHub with a Kafka enabled endpoint (Spark process writing with Kafka-libs to an EventHub, see https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/tutorials/spark/sparkProducer.scala.)

Reading from EventHubs with the EventHub lib works fine for the body (containing "value"), but the key gets lost. 

SystemProperties content looks like {"x-opt-kafka-key":"{}"}, not containing the key.

Workarounds:
- write the key to the value (EventHubs --> Body)
- use the Kafka libs to receive messages from a Kafka enabled EventHub.

Spark Version:
- 2.4.3 (Databricks Runtime 5.5)
- EventHubs library: com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.13

**Comment by nyaghma** [comment]
Kafka keys are not being properly converted to json serialized strings. PR #501 fixes this issue and includes sample code for extracting kafka keys from the SystemProperties.
