### ISSUE TITLE
Multiple writers on same stream, please update FAQs

### ISSUE THREAD

**Issue by mpsingh24** [Azure/azure-event-hubs-spark#456]
Please update the FAQs here: https://github.com/Azure/azure-event-hubs-spark/blob/master/FAQ.md
The errors "ReceiverDisconnectedException" and "The expected sequence number xxx is less than the received sequence number yyy" can also happen if the same structured stream is accessed by multiple writers. This results in the creation of 2 readers on the same consumer group. This is a common scenario in spark applications. Can you please confirm these findings and update the FAQ?

Following threads highlight this issue. Workarounds are creating a seperate reader for each writer using a separate consumer group. Or if using Databricks, use delta table as a sink for the first stream and use it as a source for the second stream.
- https://stackoverflow.com/questions/57367226/structured-streaming-writing-to-multiple-streams 
- https://stackoverflow.com/questions/54750779/reusing-an-event-hub-stream-for-multiple-queries-in-azure-data-bricks

**Comment by lcmarques** [comment]
Totally agree! This is not documented in FAQ and is a common issues in Spark Structured Stream and EventHub behavior. Multiple dataframes created over a readStream() and then materizaled in tempview and used several times in Spark SQL and then write will get a ReceiverDisconnectedException.

ehConf = {'eventhubs.connectionString' : ABC , 'eventhubs.consumerGroup' :  XPTO }
a = readStream().options(**ehConf)
...
a.createOrReplaceTempView("test")
query1 =  spark.sql(select *...... foo, bar, test where......)
query2 = spark.sql(select * from test)
...

This eventually will get the same ReceiverDisconnectedException. As mentioned before, for Databricks users, the use of Deltas will indeed help on this.
