### ISSUE TITLE
Null keys/values in properties map

### ISSUE THREAD

**Issue by sstaradubet** [Azure/azure-event-hubs-spark#459]
Using null keys or values in properties column in DataFrame cause an exception

Caused by: java.lang.NullPointerException at org.apache.spark.sql.eventhubs.EventHubsRowWriter$$anonfun$toProperties$1.apply(EventHubsWriteTask.scala:98)

It seems issue is in below [code](azure-event-hubs-spark/core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsWriteTask.scala):

```
  private def toProperties(unsafeMap: UnsafeMapData): Option[Map[String, String]] = {
    if (unsafeMap == null) {
      None
    } else {
      val keys = unsafeMap.keyArray()
      val values = unsafeMap.valueArray()
      Some(
        (0 until keys.numElements)
          .map(i => keys.getUTF8String(i).toString -> values.getUTF8String(i).toString)
          .toMap)
    }
  }
```

in invocations `keys.getUTF8String(i).toString` and `values.getUTF8String(i).toString)`

There is any reason why nullchecks are absent here ?
As user I need to send properties like that {"key1":null,"key2":"value2", "null": "value3"}.

**Comment by nyaghma** [comment]
Keys and values in the properties column cannot be null. However, as you have pointed out we need to add null checks and provide the reason for the null exception to users.
