### ISSUE TITLE
Getting last written offset from checkpoint directory

### ISSUE THREAD

**Issue by rohit21agrawal** [Azure/azure-event-hubs-spark#461]
I have a streaming spark application that continuously reads a stream of events from event hubs and writes it to a delta lake table.

In order to build fault tolerance into this application and ensure zero data loss, i am trying to figure out a way to resume querying the stream from the last written offset into the checkpoint directory.

What's the guidance for doing something like this? does the eventhub spark connector provide a way to read the checkpoint directory and figure out the offset per partition from where to resume streaming?

**Comment by nyaghma** [comment]
The connector integrates with the Spark checkpointing mechanism. You can recover the progress and state of your streaming job on failures by setting a checkpoint location. You can read more about it [here](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/spark-streaming-eventhubs-integration.md#checkpoints).
