### ISSUE TITLE
Support for .NET for Apache Spark

### ISSUE THREAD

**Issue by joperezr** [Azure/azure-event-hubs-spark#463]
The .NET team have been working on adding bindings for Apache Spark so that existing .NET developers can leverage their skills over the power of processing big data with spark. Given that a lot of .NET developers work with Azure and EventHub, are there any plans on adding support on this library for [Spark.NET](http://github.com/dotnet/spark)?

**Comment by joperezr** [comment]
cc: @sabeegrewal @sjkwak @CodingCat

**Comment by nyaghma** [comment]
We need to coordinate with the Spark.NET team on this.

**Comment by clegendre** [comment]
Hello, did you coordinate with the Spark.NET team?
