### ISSUE TITLE
Connection timeout after 300000 ms idle/inactive

### ISSUE THREAD

**Issue by ytaous** [Azure/azure-event-hubs-spark#467]
Hi, we are getting similar issue when using Structured Streaming on DataBricks platform. The SDK we are using is 2.3.12.

https://github.com/Azure/azure-event-hubs-spark/issues/340 

19/10/26 00:21:35 WARN RequestResponseOpener: requestResponseChannel.onClose error clientId[MF_0a1146_1572031611448], session[mgmt-session], link[mgmt], endpoint[$management], error com.microsoft.azure.eventhubs.EventHubException: The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:5fd5964556f4458499f35c517e4cb5e6_G0, SystemTracker:gateway5, Timestamp:2019-10-26T00:21:35

**Comment by BillMcGuinnessJLL** [comment]
@ytaous Were you able to resolve/work-around this?  I am also getting this error on DBR 6.1

**Comment by ytaous** [comment]
No, the only way is to restart the job.

**Comment by nyaghma** [comment]
@ytaous @BillMcGuinnessJLL, please upgrade to the current version (2.3.14.1) and let us know if you see the error again.

**Comment by nyaghma** [comment]
I'm closing this issue now. Please reopen if you see the same problem using the current version.

**Comment by AlexDHoffer** [comment]
I am still getting this on com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.17.

**Comment by mearupmukherjee** [comment]
Any update on this? Is it solved now?
