### ISSUE TITLE
how to reprocess the data from eventhub

### ISSUE THREAD

**Issue by guruvonline** [Azure/azure-event-hubs-spark#468]
I am reading from eventHub and writing to delta lake table after processing the data. Based on different scenarios, I might have to reporcess the  data present in eventhub. Sometime i have to reprocess by offset/enqueuedtime. I tried specifying StartingPosition(as json string), but still it picks events from EndofStream. i even tried deleting my checkpoint location folder, still it read from end. But if i delete my checkpoint folder and delta lake folder, and then start job, it picks from startofstream (as specified in StartingPosition).

How can i change my bookmark/checkpoint, once my job has processed some records.

**Comment by nyaghma** [comment]
If checkpoints are present, the starting positions are set from the checkpoint. The user-provided starting positions are used in case no checkpoints are available.
