### ISSUE TITLE
Writing to Eventhub just stops and job hangs

### ISSUE THREAD

**Issue by koksen** [Azure/azure-event-hubs-spark#469]
Bug Report:

- Actual behavior
When writing (a fairly large amount of data like 1.5 million rows) to eventhub sometimes the spark job just hangs and needs restart.
 
After digging into the logs we see it stops about after these log lines. Could there be an error in the connectionpool handling:

07 Nov 2019 12:40:41.4472019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - No clients left to borrow. EventHub name: audienceMembership, ConsumerGroup name: $Default. Creating client 80
07 Nov 2019 12:40:41.4812019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - Available clients: {0}. Total clients: 88
07 Nov 2019 12:40:41.4812019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - Available clients: {0}. Total clients: 88
07 Nov 2019 12:40:41.7982019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - No clients left to borrow. EventHub name: audienceMembership, ConsumerGroup name: $Default. Creating client 81
07 Nov 2019 12:40:41.8702019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - No clients left to borrow. EventHub name: audienceMembership, ConsumerGroup name: $Default. Creating client 82
07 Nov 2019 12:40:41.8872019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - No clients left to borrow. EventHub name: audienceMembership, ConsumerGroup name: $Default. Creating client 83
07 Nov 2019 12:40:41.8872019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - No clients left to borrow. EventHub name: audienceMembership, ConsumerGroup name: $Default. Creating client 89
07 Nov 2019 12:40:41.8872019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - **Available clients: {0}. Total clients: 89**
07 Nov 2019 12:40:41.9242019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - No clients left to borrow. EventHub name: audienceMembership, ConsumerGroup name: $Default. Creating client 84
07 Nov 2019 12:40:41.9242019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - No clients left to borrow. EventHub name: audienceMembership, ConsumerGroup name: $Default. Creating client 90
07 Nov 2019 12:40:41.9242019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - No clients left to borrow. EventHub name: audienceMembership, ConsumerGroup name: $Default. Creating client 91
07 Nov 2019 12:40:41.9672019-11-07 12:40:41 +0000  INFO  o.a.s.e.client.ClientConnectionPool - **Available clients: {0}. Total clients: 91**

- Expected behavior
Send the data to eventhub

- Spark version
2.4.3

- spark-eventhubs artifactId and version
azure-eventhubs-spark_2.11 - 2.3.14.1

**Comment by sharadkejriwal** [comment]
Facing the same issue ... 

Thread dump for one executor .. Multiple threads are blocked. and the stage is stcuk indefinitely
![image](https://user-images.githubusercontent.com/14099063/69899592-a6074700-138e-11ea-82ce-a5f576052cae.png)

Please provide an update.

**Comment by sharadkejriwal** [comment]
Is this fixed in commit https://github.com/Azure/azure-event-hubs-spark/commit/33ee66e23a89191b3a8ae3e1e745d01f95bd17fd

Commit description shows:  [Bug fix] fix IO pipe issue that causes a blocking issue on send calls
