### ISSUE TITLE
Job aborted due to stage failure

### ISSUE THREAD

**Issue by hau-mal** [Azure/azure-event-hubs-spark#470]
I am getting constantly errors like:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 21354.0 failed 4 times, most recent failure: Lost task 7.3 in stage 21354.0 (TID 231669, 10.3.2.6, executor 0): java.lang.IllegalStateException: Operation not allowed after the com.microsoft.azure.eventhubs.impl.MessageReceiver instance is Closed. 

Bug Report:r
- Spark version 2.4.4
- azure-eventhubs-spark_2.11-2.3.14.1

**Comment by sllynn** [comment]
@hau-mal I see the same. Did you find a workaround?

**Comment by nyaghma** [comment]
@hau-mal can you please share more information about the environment and the job you are running? Can you share the stack trace with us?
