### ISSUE TITLE
(Question) regarding .setMaxEventsPerTrigger() and trigger(Trigger.Once)

### ISSUE THREAD

**Issue by notlikethis1** [Azure/azure-event-hubs-spark#472]
We are using eventhub with structured streaming

to save some costs we run one particular pipleine every x hours and use 
.trigger(Trigger.Once) to process everything in the queue and wait for next scheduled run (meanwhile shutting down the cluster vm's)

This work great for test piplines, but for beta and production we will run into the issue that the default to run 1000 * {numpartitions} in one trigger may not be enough to process all data so far.

We would like to retrigger until the pipeline no longer processes the maxEventsPerTrigger setting (because the number of messages still available drops below this size), then finished that set and then stops (untill next scheduled run)

How would i go about to do such a thing?
I know about .setMaxEventsPerTrigger(), but to just set the unreasonably large doesnt feel like the way to go.

**Comment by nyaghma** [comment]
If you don't want to set the maxEventsPerTrigger to a very large value, then you need to make sure in client code that it has read all the available events. 
One way to do so is to read the last enqueued sequence number for each partition (using com.microsoft.azure.eventhubs.PartitionRuntimeInformation) every time you run the pipeline and setting the maxEventsPerTrigger value accordingly.

**Comment by ganesh-gawande** [comment]
We are also facing the same problem. We have event hub trigger job with trigger=once and it does not process all the records from the event hub. 

@nyaghma - As per your solution, do you have any sample code which we can refer for the implementation? There is not much information available on internet for this. We are using python notebook in data bricks to stream events  from event hub.

Or Is there any other solution for this?
