### ISSUE TITLE
Per partition configuration not working

### ISSUE THREAD

**Issue by b-navaneethakumar** [Azure/azure-event-hubs-spark#477]
Feature Requests: 

- What issue are you trying to solve? - Trying to use Per Partition Configuration as below.

// name is the EventHub name!
val positions = Map(
  new NameAndPartition(name, 0) -> EventPosition.fromStartOfStream,
  new NameAndPartition(name, 1) -> EventPosition.fromSequenceNumber(100L)
)

val cs = "YOUR.CONNECTION.STRING"
val ehConf = EventHubsConf(cs)
  .setStartingPositions(positions)
  .setStartingPosition(EventPosition.fromEndOfStream)
  
  

- How do you want to solve it?  - No idea how to solve this 

- What is your use case for this feature?  - When there is multiple partition in EH , we cant insist EH to read from particular offset. 

Bug Report:

- Actual behavior - setStartingPositions is not working ,when setStartingPosition is set 
- Expected behavior - setStartingPositions should take high priority . But when setStartingPositions this is given and setStartingPosition is ignored ,Default values are taken for setStartingPosition
- Spark version - 2.4.0 
- spark-eventhubs artifactId and version 

 "com.microsoft.azure" %% "azure-eventhubs-spark" % "2.3.14",
   "com.microsoft.azure" % "azure-eventhubs" % "3.0.2",

**Comment by nyaghma** [comment]
If checkpoints are present, then the user-provided start positions are ignored and the start positions are read from the existing checkpoints. 
Otherwise, the start position is set to the user-provided value if the value points to a present event. If the provided value points to an expired event (due to the retention period), the start position would be set to the sequence number of the first present event in the partition.

**Comment by b-navaneethakumar** [comment]
No checkpoint is enabled.

And it's freshly created hub. So there is no chance of message expire.

If we are not giving setstartingposition by default it goes to latest
position. Even though we provide setstartingpositions.

**Comment by nyaghma** [comment]
The default starting position for each partition is the latest position unless a specific starting position is set by using either setstartingposition or setstartingpositions.

I'm trying to produce the issue you are facing, but haven't been able to do so. Could you please share more information about your environment/setup?

**Comment by nyaghma** [comment]
Closing the issue for now. In case you still see the issue, please share more information with me to investigate further.
