### ISSUE TITLE
com.microsoft.azure.eventhubs.ReceiverDisconnectedException

### ISSUE THREAD

**Issue by uttamu2812** [Azure/azure-event-hubs-spark#496]
Hi I  am consuming only one consumer group in single instance. 
               EventProcessorHost host ;
		EventProcessorOptions options = new EventProcessorOptions();
		options.setExceptionNotification(new ErrorNotificationHandler());
... init the host.
host.registerEventProcessor(RestaurantEventProcessor.class,options).get();

some time getting error like below.
 @com.microsoft.azure.eventhubs.ReceiverDisconnectedException: Receiver 'nil' with a higher epoch '59' already exists. Receiver 'nil' with epoch 58 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:3f32e569-38a6-4e91-9fe1-1557381f3e19_B24, SystemTracker:drs-uw-ehns-q:eventhub:drsrefdata-uw-eh-q~16383|phoenix, Timestamp:2020-04-07T21:16:11 Reference:f8d048a1-d97a-4152-8b37-db734610f26c, TrackingId:2a15e5a4-ad66-4aab-9914-f2b5dd7f45d3_B24, SystemTracker:drs-uw-ehns-q:eventhub:drsrefdata-uw-eh-q~16383|phoenix, Timestamp:2020-04-07T21:16:11 TrackingId:00bea43a436d498f91ef9a9a6ed2aa02_G18, SystemTracker:gateway5, Timestamp:2020-04-07T21:16:11, errorContext[NS: drs-uw-ehns-q.servicebus.windows.net, PATH: drsrefdata-uw-eh-q/ConsumerGroups/phoenix/Partitions/1, REFERENCE_ID: 8f1cc5_a02_G18_1586294171562, PREFETCH_COUNT: 300, LINK_CREDIT: 0, PREFETCH_Q_LEN: 0]

**Comment by sjkwak** [comment]
@uttamu2812 - the error is a transient error and it can happen while a partition is being rebalanced. Are you seeing the issue happening continuously? 
Btw, the library that you're using is EventProcessorHost SDK and you can use the following link to report the issue and get help.
https://github.com/Azure/azure-sdk-for-java/issues
