### ISSUE TITLE
Application properties of type String are deserialized with extra double quotes

### ISSUE THREAD

**Issue by neilhuiz** [Azure/azure-event-hubs-spark#511]
Hi there, it appears that the EventHub client is not doing the right thing when deserializing the application properties map (i.e. `properties` column in the RDD/DF). When a string application property is passed from the sender, it is deserialized with extra quotes wrapped around it. As an example, if I send an event with the application property `MyProperty` with a value of `MyValue`, in my Scala code, I get back a property map with `(MyProperty -> "MyProperty")`:

```
+----------+---------+
|        _1|       _2|
+----------+---------+
|MyProperty|"MyValue"|
+----------+---------+
```

The expected behavior would be without the quotes:

```
+----------+-------+
|        _1|     _2|
+----------+-------+
|MyProperty|MyValue|
+----------+-------+
```

My sender is a C# application and is relying on the default serialization behavior when calling `EventData.Properties.Add("MyProperty", "MyValue")`. Other types (e.g. `bool`, `int`) don't exhibit this behavior, though all are turned into strings on the reader's side. If I may speculate, it appears to be related to the use of `org.json4s.jackson.Serialization.write()` in [EventHubsSourceProvider](https://github.com/Azure/azure-event-hubs-spark/blob/master/core/src/main/scala/org/apache/spark/sql/eventhubs/EventHubsSourceProvider.scala) (see ~line 192). Annoyingly, `org.json4s.jackson.Serialization.write("test") == "\"test\""`.

I verified this behavior under both 2.3.13 and 2.3.15 versions of the `azure-eventhubs-spark` package. I also verified under both 2.11.12 and 2.11.8 versions of Scala. Here is Scala code that reproduces the behavior:

```
val connectionString = ConnectionStringBuilder("{secret sauce}")
    .build

val ehConf = EventHubsConf(connectionString)
    .setConsumerGroup("warm")
    .setStartingPosition(EventPosition.fromEnqueuedTime(Instant.now))

val events = spark
    .readStream
    .format("eventhubs")
    .options(ehConf.toMap)
    .load()
    .toDF()

val query = events
    .flatMap(r => r.getAs[Map[String, String]]("properties"))
    .writeStream
    .format("console")
    .start()

query.awaitTermination()
```

And the C# code:

```
var hub = EventHubClient.CreateFromConnectionString("{secret sauce}");
var evt = new EventData(Encoding.UTF8.GetBytes(payload.ToString()));
evt.Properties.Add("MyProperty", "MyValue");
await hub.SendAsync(evt);
```

Contents of `build.sbt`:

```
dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-core" % "2.9.5" % Provided
dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.5" % Provided
dependencyOverrides += "com.fasterxml.jackson.module" % "jackson-module-scala_2.11" % "2.9.5" % Provided
dependencyOverrides += "org.wildfly.openssl" % "wildfly-openssl" % "1.0.7.Final" % Provided
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-sql" % "2.4.3" % Provided,
  "org.apache.spark" %% "spark-core" % "2.4.3" % Provided,
  "org.apache.spark" %% "spark-streaming" % "2.4.5" % Provided,
  "com.databricks" %% "dbutils-api" % "0.0.4" % Provided,
  "org.apache.hadoop" % "hadoop-common" % "3.2.0" % Provided,
  "org.apache.hadoop" % "hadoop-azure" % "3.2.0" % Provided,
  "org.apache.hadoop" % "hadoop-mapreduce-client-core" % "3.2.0" % Provided,
  "io.delta" %% "delta-core" % "0.3.0" % Provided,
  "com.microsoft.azure" %% "azure-eventhubs-spark" % "2.3.13" % Provided,
  "com.googlecode.json-simple" % "json-simple" % "1.1" % Provided
)
```

**Comment by neilhuiz** [comment]
Doing a simple blind mapping like you propose will break for all other types. For example, calling `slice()` on a serialized integer value will likely cause either an exception (if the value is too short) or a logical error when `123` becomes `2`.

In my mind, a better solution would be to skip the serialization of values that are already strings. The change is relatively simple, though for some users may represent a breaking change because they have been dealing with the extra quotes in their code. Check out #514 for my idea of how to better deal with this.

**Comment by davad** [comment]
I'm having the same issue.

Also, if you pull messages from one EventHub and immediately queue them in another, those extra quotes get pushed into the serialized message. It's a headache.

**Comment by nyaghma** [comment]
@neilhuiz and @davad, thanks for the discussion. My point was if the user knows the type of the value in the property bag, he/she can handle it on the client-side. However, thanks to the discussion here there might be other issues with the current implementation.
@neilhuiz, the PR https://github.com/Azure/azure-event-hubs-spark/pull/514 that you submitted failed the Travis CI build, so I submitted another PR https://github.com/Azure/azure-event-hubs-spark/pull/516 and added @sjkwak to review it.
