### ISSUE TITLE
Spark structured streaming hang

### ISSUE THREAD

**Issue by xinxinzhan** [Azure/azure-event-hubs-spark#515]
We are using the latest version connector com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.15.

The spark streaming job write to eventhub always run for some time then got stuck. 

Below are the thread dump of the threads that seem to have problem:

![image](https://user-images.githubusercontent.com/41314539/84469913-bb055100-acb4-11ea-8427-ff425679ded5.png)

![image](https://user-images.githubusercontent.com/41314539/84469999-e720d200-acb4-11ea-8f24-029d28d68457.png)

**Comment by nyaghma** [comment]
@xinxinzhan, could you please share more information about the job that you are running with us?
