### ISSUE TITLE
Not compatible with azure-client-authentication v1.6.15

### ISSUE THREAD

**Issue by raksit31667** [Azure/azure-event-hubs-spark#526]
## Context (Environment)
Running with following environments:
- Azure Databricks runtime 5.5 LTS
- Scala v2.11
- Spark v2.4.3
- azure-eventhubs-spark_2.11:2.3.16 Maven
- azure-client-authentication:1.6.15 Maven
- azure-keyvault:1.2.2 Maven

## Expected Behavior
Databricks automated cluster should be running fine.

## Current Behavior
Cluster fails to execute with following exceptions:

```
Library installation failed for library maven { coordinates: "com.microsoft.azure:azure-client-authentication:1.6.15" } . Error messages: Could not resolve library.
```

## Possible Solution
My workaround is to downgrade version to azure-eventhubs-spark_2.11:2.3.13.

**Comment by nyaghma** [comment]
@raksit31667 The version 2.3.16 uses the azure-eventhubs java SDK 3.2.0 which uses azure-client-authentication version 1.7.3. That's why you see the library installation failure when trying to use azure-eventhubs-spark_2.11:2.3.16 with azure-client-authentication:1.6.15.
