### ISSUE TITLE
Support Service Principal Authentication

### ISSUE THREAD

**Issue by mgyucht** [Azure/azure-event-hubs-spark#531]
- What issue are you trying to solve?
I would like to use a single service principal in Azure Active Directory to access EventHubs using Spark.

- How do you want to solve it?
It seems like we could use this library to do this: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.0.0-beta.6/index.html, but I'm not very familiar with this library.

- What is your use case for this feature?
We are building a pipeline using Azure Databricks which reads data from EventHubs and then stores the results in various storage accounts. Today, service principal authentication is supported for ADLS v2 (see https://docs.databricks.com/data/data-sources/azure/azure-datalake-gen2.html), so we don't need to manage separate tokens for each storage container we store data into. It would be great if this were also extensible for EventHubs: that way, we could configure a single secret which is used for accessing both EventHubs and storage accounts.

**Comment by nyaghma** [comment]
Support for AAD authentication has been added to the library. Please check [this document](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/use-aad-authentication-to-connect-eventhubs.md) for more information.

**Comment by ganeshthiagarajan** [comment]
@nyaghma - Thanks for the documentation - Is there any instructions about how to achieve AAD Authentication using Service  Principal while using python (pyspark)
https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/PySpark/structured-streaming-pyspark.md

**Comment by nyaghma** [comment]
@ganeshthiagarajan That's not included in the current document. We'll update it and add instructions for pyspark as well.

**Comment by jonathan-loe** [comment]
@nyaghma I'm keen to know how to do this too. may I know when the instructions is ready for pyspark?

**Comment by j2k850** [comment]
I am keen as well. Is there any documentation available showing how to do this in PySpark.

**Comment by agungw132** [comment]
is there any update on documentations how to do it in pyspark?
