### ISSUE TITLE
Connection timeout after 300000 ms idle/inactive 

### ISSUE THREAD

**Issue by AlexDHoffer** [Azure/azure-event-hubs-spark#537]
``20/09/15 03:51:03 INFO BaseLinkHandler: onLinkRemoteClose clientName[mgmt], linkName[mgmt:sender], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:9f1553a96a8a49cd917ba7d963ad8353_G15, SystemTracker:gateway5, Timestamp:2020-09-15T03:51:03]``

Re-opening https://github.com/Azure/azure-event-hubs-spark/issues/467

We are on com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.17 and still seeing this problem. 

Incoming data is clearly still coming (so the connection shouldn't be idle):

![image](https://user-images.githubusercontent.com/19369483/93165068-ee9ab180-f6cf-11ea-8deb-97d273e5ae93.png)

We are using PySpark.

**Comment by nyaghma** [comment]
@AlexDHoffer, The message indicates that the connection to eventhub has been inactive for 5 minutes. This could happen if a job blocks at any point of batch execution, even after receiving events from eventhub. One way to check is to find the task ID that hasn't finished in the driver log and check the corresponding executor log to see if the task has completed receiving messages from the eventhub. [This log ](https://github.com/Azure/azure-event-hubs-spark/blob/90d70928d9c738923afe5d08557e0a61c9c7188d/core/src/main/scala/org/apache/spark/eventhubs/client/CachedEventHubsReceiver.scala#L281) shows if a task has finished receiving events.
