### ISSUE TITLE
Package azure-eventhubs-spark_2.11 Version 2.3.17 depends on scala 2.12

### ISSUE THREAD

**Issue by koksen** [Azure/azure-event-hubs-spark#539]
The Package on maven depends on the wrong scala version. It should depend on scala 2.11

https://repo1.maven.org/maven2/com/microsoft/azure/azure-eventhubs-spark_2.11/2.3.17/azure-eventhubs-spark_2.11-2.3.17.pom

SBT:
scalaVersion := "2.11.12"
val sparkVersion = "2.4.7"
"com.microsoft.azure" % "azure-eventhubs-spark_2.11" % "2.3.17",

Error:
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/C:/source/cdp.audience.engine/"), "root"):
[error]    org.scala-lang.modules:scala-java8-compat _2.11, _2.12
[error] stack trace is suppressed; run 'last update' for the full output
[error] stack trace is suppressed; run 'last ssExtractDependencies' for the full output
[error] (update) Conflicting cross-version suffixes in: org.scala-lang.modules:scala-java8-compat
[error] (ssExtractDependencies) Conflicting cross-version suffixes in: org.scala-lang.modules:scala-java8-compat

**Comment by kklimexk** [comment]
What is the status of this issue? For now it's impossible to use this package.

**Comment by nyaghma** [comment]
We will fix the issue in the next release.

**Comment by nyaghma** [comment]
The issue has been fixed in version 2.3.18.
