### ISSUE TITLE
Issue: java.util.concurrent.TimeoutException: Futures timed out after [5 minutes]

### ISSUE THREAD

**Issue by DennisSong123** [Azure/azure-event-hubs-spark#546]
Feature Requests: 

- What issue are you trying to solve? 
Running a databricks sample code (https://github.com/solliancenet/microsoft-learning-paths-databricks-notebooks/blob/master/data-engineering/DBC/10-Structured-Streaming.dbc), the stream will stuck on "stream initializing", the stage will retry and get into error "java.util.concurrent.TimeoutException: Futures timed out after [5 minutes]"

If we change datasource to small file, the spark stream can be ran. 

Bug Report:

- Actual behavior
stream initializing stuck, and will report error "java.util.concurrent.TimeoutException: Futures timed out after [5 minutes]"
- Expected behavior
stream initializing complete
- Spark version
spark 3
- spark-eventhubs artifactId and version
com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.17

**Comment by nyaghma** [comment]
The Future Timeout exception happened due to an issue in the underlying Java SDK. PR #604 updated the Java SDK to version 3.3.0 which has fixed this issue. This PR has been merged to the master branch and been released in version 2.3.20.
