### ISSUE TITLE
Cannot write data to a specific partition

### ISSUE THREAD

**Issue by zzgzy** [Azure/azure-event-hubs-spark#547]
Feature Requests: 

- What issue are you trying to solve?
cannot write data to a specific partition
- How do you want to solve it? 
want to understand if it's a bug or the I use it in a wrong way
- What is your use case for this feature? 
want to send some signal data to event hub and have to send to every partition.

Bug Report:

- Actual behavior
I specified the "partitionId" column (with “body”) in the data query and send the data to 3 different partitions. When processing the data from a c# app, I noticed that the signal messages are not present in every partitions.
```
    messages
      .select("partitionId", "body")
      .write
      .format("eventhubs")
      .option("checkpointLocation", XXX)
      .options(ehConf.toMap).save()   // messages: Dataset[(String, String)]
```
- Expected behavior
The messages should be sent to every single partitions defined by the partitionId column.
- Spark version
2.4 on HDInsight
- spark-eventhubs artifactId and version
azure-eventhubs-spark_2.11:2.3.15

**Comment by nyaghma** [comment]
The change is included in version 2.3.18.
