### ISSUE TITLE
Need namespace in `ThrottlingStatusPlugin` functions

### ISSUE THREAD

**Issue by tilumi** [Azure/azure-event-hubs-spark#554]
Feature Requests: 

- What issue are you trying to solve?
    We need namespace information in [`onPartitionsPerformanceStatusUpdate`](https://github.com/Azure/azure-event-hubs-spark/blob/90d70928d9c738923afe5d08557e0a61c9c7188d/core/src/main/scala/org/apache/spark/eventhubs/utils/ThrottlingStatusPlugin.scala#L31) & [`onBatchCreation`](https://github.com/Azure/azure-event-hubs-spark/blob/90d70928d9c738923afe5d08557e0a61c9c7188d/core/src/main/scala/org/apache/spark/eventhubs/utils/ThrottlingStatusPlugin.scala#L27)
- How do you want to solve it? 
- What is your use case for this feature? 
We have a plugin deployed to different regions, so need know which namespace the plugin reading

**Comment by nyaghma** [comment]
The change is included in version 2.3.18.
