### ISSUE TITLE
Add EH namespace information to client logging and d stream info 

### ISSUE THREAD

**Issue by jgiardin** [Azure/azure-event-hubs-spark#556]
Thanks for filing an issue with us! Below are some guidelines when filing an issue. In general, the more detail the better!

Feature Requests: 
- Add EH namespace information to client logging. Any logging that contains NameAndPartition should include Namespace, since EventHub name may not be unique across namespaces.
- Add EH namespace information to the "Input Metadata" information on the spark streaming UI.

Assuming there are no issues, it seems like we can add namespace to the NameAndPartition and update the ToString function in OffsetRange to get most of this plumbed through.

**Comment by reminia** [comment]
Hi, is anyone working on this? Namespace info is essential to distinguish unique eventhub instance.

**Comment by nyaghma** [comment]
PR #600 has added namespace to the logs. This PR has been released in version 2.3.19.

**Comment by jgiardin** [comment]
Thanks for this change, but it does not solve the problem completely. Namespace is still not available in things like "MetricPlugin" interface or "OffsetRange" toString.

**Comment by tilumi** [comment]
@nyaghma Could you reopen this issue? the namespace is still not available in MetricPlugin
