### ISSUE TITLE
Accessing Event Hub Schema Registry through Event Hubs Connector

### ISSUE THREAD

**Issue by mdrakiburrahman** [Azure/azure-event-hubs-spark#567]
Hi Team,

I understand that the Schema Registry for EH is currently [in preview](https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview), and there is some work-in-progress to consume from the Schema Registry from the Kafka surface (such as [this](https://github.com/arerlend/azure-schemaregistry-spark)).

Would you be able to advise if it's possible to leverage the Schema Registry using the Event Hubs Connector for Spark (i.e. this repo)?

E.g. - something like this:
` 

     val props: HashMap[String, String] = new HashMap()
         props.put("schema.registry.url", SCHEMA_REGISTRY_URL)
         props.put("schema.registry.tenant.id", SCHEMA_REGISTRY_TENANT_ID)
         props.put("schema.registry.client.id", SCHEMA_REGISTRY_CLIENT_ID)
         props.put("schema.registry.client.secret", SCHEMA_REGISTRY_CLIENT_SECRET)

     val df = spark.readStream
          .format("eventhubs")  // leveraging the Event Hubs connector instead of kafka
          .options(**eventHubsConf) 
          .load()

     df.select(from_avro($"value", "[schema guid]", props)) 
          .writeStream
          .outputMode("append")
          .format("console")
          .start()
`
Please let me know if this is supported (any code reference would be amazing).

If the schema registry is not supported by the connector yet, is this perhaps in the roadmap?

Thank you.

**Comment by arerlend** [comment]
Hey Raki - yes, from_avro will support both EH and Kafka payloads.  Fundamentally, you're only going to be looking at the EH message body or the Kafka message value - from_avro will be able to read either for them.

**Comment by mdrakiburrahman** [comment]
@arerlend: Thank you, Arthur!
