### ISSUE TITLE
Get last written offset from checkpoint directory

### ISSUE THREAD

**Issue by davew-msft** [Azure/azure-event-hubs-spark#578]
This is related to [Issue 461](https://github.com/Azure/azure-event-hubs-spark/issues/461).  

I have implemented a databricks/spark application that streams data from EH and uses a spark checkpoint directory for some stateful processing.  Works great.  

But, sometimes we need to change the schema or code and we've found if we don't delete the checkpoint folder the checkpoint doesn't work correctly.  My assertion is supported by [this documentation](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/spark-streaming-eventhubs-integration.md#checkpoints) and [this too](https://kb.databricks.com/streaming/ss-read-from-last-offset.html).  As soon as we delete the checkpoint folder we lose the offset information for the next restart.

What we'd like to do is have a mechanism where we can:
* stop the notebook
* determine the last processed offset (probably by reading the checkpoint folder)
* deploy our new notebook/code
* delete the checkpoint folder
* restart the stream by passing in the offset as determined above.  

So, is this possible? Is there a way to read the checkpoint folder and determine the offset?  Or an API?

**Comment by nyaghma** [comment]
The checkpoint directory has two subdirectories: offsets, and commits. You can find the last processed offsets for each batch in a file with the batch id. Also, you can find the latest committed batch under the commits directory. Therefore, you can find the file with the highest number in the commits directory to find out the latest committed batch, and then find the latest offsets read in that batch in the file with the same number under the offsets directory.
