### ISSUE TITLE
Databricks 8 / Spark 3.1 Release?

### ISSUE THREAD

**Issue by redcape** [Azure/azure-event-hubs-spark#588]
Hello,

Is there a version usable with Databricks 8 / Spark 3.1? https://docs.databricks.com/release-notes/runtime/8.0.html

Thank you!

**Comment by abij** [comment]
Yes, I'm using `com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.18`

Note: when you are running jobs, you cannot refer to maven! I have uploaded these jar to dbfs and linked in jobs:
- [azure-eventhubs-spark_2.12-2.3.18.jar](https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs-spark_2.12/2.3.18)
- [azure-eventhubs-3.2.2.jar](https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs/3.2.2)
- [scala-java8-compat_2.12-0.9.0.jar](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-java8-compat_2.12/0.9.0)
- [proton-j-0.33.4.jar](https://mvnrepository.com/artifact/org.apache.qpid/proton-j/0.33.8)

I have jobs running with Runtime 8.0 (spark 3.1.1)

**Comment by nyaghma** [comment]
com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.18 should work fine with Databricks 8.
