### ISSUE TITLE
Spark streaming runs into error after short inactivity of incoming events to Event Hubs - Java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by FeFi1989** [Azure/azure-event-hubs-spark#591]
Hi everyone,

we are building a streaming solution using Azure Databricks where we ingest streaming data that is extracted to Azure Event Hubs.

When there is no steady inflow of streaming events to Event Hubs, the streaming query runs into an error. This usually happens after just a few minutes. We have set all possible timeout intervals in the configuration to 9000s, but the error persists. 
We have created a workaround by sending empty data in short intervals to Event Hubs. This makes the solution more stable but it still runs into an error for example when the extractor system is in maintenance.
This issue looks very similar to [issue-411](https://github.com/Azure/azure-event-hubs-spark/issues/411) and [issue-413](https://github.com/Azure/azure-event-hubs-spark/issues/413) and was supposed to be fixed with [PR-419](https://github.com/Azure/azure-event-hubs-spark/pull/419). 

![error](https://user-images.githubusercontent.com/52912841/114874911-11737c80-9dfd-11eb-830b-75c192fc5de9.png)

We are using the following versions
com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.18
com.microsoft.azure:msal4j:1.8.1

Please find below the detailed error message and the code being used:

_at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:89) at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) Caused by: com.microsoft.aad.msal4j.MsalClientException: java.net.SocketTimeoutException: Read timed out at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:68) at com.microsoft.aad.msal4j.OAuthHttpRequest.send(OAuthHttpRequest.java:33) at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:36) at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:119) at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59) ... 7 more Caused by: java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) at java.net.SocketInputStream.read(SocketInputStream.java:171) at java.net.SocketInputStream.read(SocketInputStream.java:141) at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476) at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470) at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1151) at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:72) at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:838) at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) at java.io.BufferedInputStream.read(BufferedInputStream.java:345) at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:743) at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490) at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488) at java.security.AccessController.doPrivileged(Native Method) at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487) at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) at com.microsoft.aad.msal4j.DefaultHttpClient.readResponseFromConnection(DefaultHttpClient.java:107) at com.microsoft.aad.msal4j.DefaultHttpClient.executeHttpPost(DefaultHttpClient.java:63) at com.microsoft.aad.msal4j.DefaultHttpClient.send(DefaultHttpClient.java:37) at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:86) at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:64) ... 12 more_

_____________________________

from pyspark.sql.types import *
from pyspark.sql.functions import *
from py4j.java_gateway import java_import
import json

eh_conf = {
  "eventhubs.connectionstring": sc._jvm.org.apache.spark.eventhubs.EventHubsUtils.encrypt("Endpoint=sb://abc.net;EntityPath=xyz"),
  "eventhubs.consumergroup": "$Default",
  "eventhubs.useaadauth": True,
  "eventhubs.aadauthcallback": "com.abc.def.demo.AuthBySecretCallBack",
  "eventhubs.operationTimeout": sc._jvm.java.time.Duration.ofSeconds(9000),
  "eventhubs.receivertimeout": sc._jvm.java.time.Duration.ofSeconds(9000),
  "eventhubs.maxsilenttime": sc._jvm.java.time.Duration.ofSeconds(9000),
}

startTime = "2021-01-01T00:00:00.000000Z"
endTime = "2099-12-31T00:00:00.000000Z"

startingEventPosition = {
"offset": None, #not in use
"seqNo": -1, #not in use
"enqueuedTime": startTime,
"isInclusive": True
}

endingEventPosition = {
"offset": None, #not in use
"seqNo": -1, #not in use
"enqueuedTime": endTime,
"isInclusive": True
}

eh_conf["eventhubs.startingPosition"] = json.dumps(startingEventPosition)
eh_conf["eventhubs.endingPosition"] = json.dumps(endingEventPosition)

java_import(spark.sparkContext._jvm, "com.abc.def.demo.AuthBySecretCallBack")
spark.sparkContext._jvm.AuthBySecretCallBack.setClientSecret(dbutils.secrets.get(scope="MY_SCOPE", key="MY_SCOPE_SECRET"))
spark.sparkContext._jvm.AuthBySecretCallBack.setClientId(dbutils.secrets.get(scope="MY_SCOPE", key="MY_SCOPE_SECRET"))

read_schema = StructType([
  StructField("checkGroup", StringType(), True),
  StructField("timestamp", TimestampType(), True)])

streamingInputDF = (
  spark
    .readStream                       
    .format("eventhubs")
    .options(**eh_conf)
    .load()
)

streamingBodyDF = (
  streamingInputDF
    .selectExpr("cast(Body as string) as json")
    .select(from_json("json", read_schema)
    .alias("data"))
    .select("data.*"))

query = (
  streamingBodyDF 
    .writeStream
    .format("json")        
    .queryName("stream_to_dbfs")     
    .outputMode("append")
    .option("path", "/FileStore/abc/sink")
    .option("checkpointLocation", "/FileStore/abc/chkpt_dir")
    .start()
)

Thanks for your efforts,

Felix

**Comment by nyaghma** [comment]
This issue is not related to issues 411 or 413. There is no code from the connector on the stack and it seems the issue has happened in "com.microsoft.aad.msal4j" component.
