### ISSUE TITLE
Py4JError: org.apache.spark.eventhubs.EventHubsUtils.encrypt does not exist in the JVM

### ISSUE THREAD

**Issue by avijitey** [Azure/azure-event-hubs-spark#594]
Hi,

I am trying to establish the connection string and using the below code in azure databricks

startEventHubConfiguration = {
  'eventhubs.connectionString' : sc._jvm.org.apache.spark.eventhubs.EventHubsUtils.encrypt(startEventHubConnectionString)  
}

and getting the below error:

Py4JError: org.apache.spark.eventhubs.EventHubsUtils.encrypt does not exist in the JVM

I am using the azure_eventhubs_spark_2_12_2_3_17.jar. 

Please help.

**Comment by nyaghma** [comment]
Could you please provide more information about your databricks enviroment?

**Comment by tahaum** [comment]
I am receiving the same error. What do you need to know about the Databricks environment?

**Comment by tahaum** [comment]
Btw, I'm using the _com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.18_ Maven library

**Comment by nyaghma** [comment]
@tahaum Can you please share the runtime version you are using for your cluster?

**Comment by tahaum** [comment]
Tested some more, and downloading the JARs and installing them as workspace libraries does not work for me as I get the error in this issue.  On the other hand, installing them as a Maven library works for both 2.3.17 and 2.3.18 (Databricks runtime 8.2 ML (Apache Spark 3.1.1, Scala 2.12))

**Comment by nyaghma** [comment]
Seems to be related to the library installation rather than an issue in the library since getting the library from Maven has resolved the issue.
