### ISSUE TITLE
Can't get spark-streaming-eventhubs_2.11 to work with Jupyter in HDInsight 3.6 (Spark 2.1)

### ISSUE THREAD

**Issue by olegoga** [Azure/azure-event-hubs-spark#80]
I can launch spark-shell with  
```
spark-shell --packages com.microsoft.azure:spark-streaming-eventhubs_2.11:2.0.5
```
which works fine, but when I use the same package in Jupyter with 
```
%%configure -f
{ "conf": {"spark.jars.packages": "com.microsoft.azure:spark-streaming-eventhubs_2.11:2.0.5" }}
```
It always fails with the cryptic error:
> The code failed because of a fatal error:
> 	Session 31 unexpectedly reached final status 'dead'. See logs:

Or sometimes with this one:

> The code failed because of a fatal error: Status 'shutting_down' not supported by session..

Also interesting that streaming-eventhubs_2.10 does work in Jupyter

**Comment by CodingCat** [comment]
what does the log say?

**Comment by olegoga** [comment]
Full yarn log: [https://pastebin.com/raw/vAZ3Mc5n](https://pastebin.com/raw/vAZ3Mc5n)

ERROR ApplicationMaster: User class threw exception: scala.reflect.internal.FatalError: object Predef does not have a member classOf

However,I'm not sure that this error is the cause, it looks like it happens when the session is shutting down, but it's not clear what caused the shutdown. I suspect the the problem is with livy, because it only happens when livy is used, but livy also has nothing interesting in it's logs.

Livy logs: https://pastebin.com/raw/map82cDF

Perhaps there are more log files I can be looking at, but I'm not sure what they can be

**Comment by CodingCat** [comment]
what's your spark version? it looks like you are using scala 2.10 in the cluster and load this lib which relies on 2.11

**Comment by olegoga** [comment]
Where do you see a mention of 2.10? According to Spark History, it's 2.11. Scala version is 2.11.8 and most of the packages it loads have _2.11 suffix. Perhaps livy is complied with 2.10 and that creates incompatibility?

**Comment by CodingCat** [comment]
I am just guessing, because of `scala.reflect.internal.FatalError: object Predef does not have a member classOf`

**Comment by olegoga** [comment]
I think I found what's going on. Here's the dependencies of spark-streaming-eventhubs:
spark-streaming-eventhubs_2.11 » 2.0.5
 spark-streaming_2.11 v2.0.2
  spark-tags_2.11 v2.0.2
   scalatest_2.11 v2.2.6
    **scala-reflect v2.11.7**

This chain of dependencies brings binaries compiled with Scala 2.11.7 into Spark complied with Scala 2.11.8. 
The issue has been already reported as Livy [issue 323](https://issues.cloudera.org/browse/LIVY-323)
 here and they created a [fix/workaround](https://github.com/cloudera/livy/commit/07f6072f9d90ec970a1f9fbaccf0452f3a783538) to be included in livy 0.4 (not yet released). 

I still didn't find a workaround until livy 0.4 is released.

**Comment by CodingCat** [comment]
that fix may be worth more discussions.....scala-reflect is a package separating from scala core package, it might not be in the class path....

I do not understand the problem here, there is some breaking changes between scala-reflect 2.11.7 and 2.11.8?

**Comment by matw** [comment]
@olegoga I was getting the same fatal error when including certain JARs in a Jupyter notebook (both with a local Livy server and on HDInisght). Similarly, I had no problem when submitting to the Spark shell.

Here's a workaround that solved the problem for me:

```
%%configure -f
{"conf": {  
  "spark.jars.packages": "<groupId>:<artifactId>:<version>",
  "spark.jars.excludes": "org.scala-lang:scala-reflect,org.apache.spark:spark-tags_2.11"
}}
```
Just exclude both the scala-reflect and spark-tags artifacts.

**Comment by syedhassaanahmed** [comment]
I'm facing exactly the same issue with Jupyter in HDInsight 3.6

%%configure -f
{
    "conf": { 
        "spark.jars.packages": "com.microsoft.azure:spark-streaming-eventhubs_connector_2.11:2.1.4",
        "spark.jars.excludes": "org.scala-lang:scala-reflect,org.apache.spark:spark-tags_2.11"
    }
}

@matw Excludes didn't help in my case
@olegoga Did you find a solution to this issue?

**Comment by romitgirdhar** [comment]
I received the same error. However, I realized that my JAR name and version were incorrect. The (current) correct JAR package is "com.microsoft.azure:azure-eventhubs-spark_2.11:2.1.6". 
I agree though that the error message is cryptic. Can folks please try to run the job in Jupyter again using the right JAR name and version? Thanks!

**Comment by syedhassaanahmed** [comment]
Thanks @romitgirdhar I can confirm my Jupyter job works using the correct jar name and version!

**Comment by sabeegrewal** [comment]
The change to the the artifactId came after this issue was created, so at the time they were using the correct info. I was under the impression that this issue was happening due to a bug in Livy. 

@romitgirdhar and @syedhassaanahmed, I just want to confirm, you're able to use this library with Jupyter notebooks in HDInsight? If you could post exactly how you imported the package here that would be great for people that run into this issue down the road! 

I appreciate the help :)

**Comment by syedhassaanahmed** [comment]
@sabeegrewal This is how I imported the package in Jupyter notebook, HDInsight

```
%%configure -f
{
    "conf": { 
        "spark.jars.packages": "com.microsoft.azure:azure-eventhubs-spark_2.11:2.1.6",
        "spark.jars.excludes": "org.scala-lang:scala-reflect,org.apache.spark:spark-tags_2.11"
    }
}
```

**Comment by romitgirdhar** [comment]
Done! Just submitted a PR with a walkthrough of using the JAR in Jupyter using the PySpark3 kernel. Please review and approve at your earliest convenience.
